### ISSUE TITLE
DangerReleasingSubstance as part of composition

### ISSUE THREAD

**Issue by dirk-qualisys** [esdscom/sdscom-xml#1]
Currently, DangerReleasingSubstance[AdrRidAdn|Imdg|Icao] is a phrase field. This should contain the names of all applicable substances as well as additions, as defined in the transport carrier specific documentation. 
For IT systems however, it is necessary to link to specific substance data sets and mark them as the danger realeasing substance. Usually both source and target system will have this, but SDScom cannot transfer this info. Thus, I propose to add in 

/DatasheetFeed/Datasheet/Composition/Mixture/Component/

the boolean fields 

TransportInformation/IsDangerReleasingSubstanceAdrRidAdn
TransportInformation/IsDangerReleasingSubstanceImdg
TransportInformation/IsDangerReleasingSubstanceIcao

**Comment by nils-eska** [comment]
Has been implemented in SDSComXmlCT4.2.0.xsd
