### ISSUE TITLE
Fix the spelling error for NationalLegislationDemnark

### ISSUE THREAD

**Issue by DuckZer0** [esdscom/sdscom-xml#103]
In SDSComXML.xsd the M and N of Denmark have been switched

**Comment by dirk-qualisys** [comment]
How embarrassing! Classified as Refactoring because there is no impact on transmittable content.

**Comment by dirk-qualisys** [comment]
Thanks again for pointing this out. If you have deeper insight in DK regulations, may I encourage you to add an issue for this?
