### ISSUE TITLE
Use of PhysicalChemicalUnitValue in section 9 should be revised

### ISSUE THREAD

**Issue by thegbom** [esdscom/sdscom-xml#104]
Boiling point of a substance has to do with pressure and temprature. Today it is defined as PhysicalChemicalUnitValue, but should be defined as PhysChemUnitValueWithTemperature. The same goes for meldingpoint, and there may be others.

**Comment by thegbom** [comment]
I think the solution would be to add a new type: PhysChemUnitValueWithPressure. That would solve many of the problems in Section 9.

**Comment by dirk-qualisys** [comment]
That is what we did in issue #65, and pressure is now part of PhysChemUnitValue. Please confirm, or am I misunderstanding you?

**Comment by thegbom** [comment]
Please forgive me. It did not read the previous issues. This issue can be closed.
