### ISSUE TITLE
Revise the definition of PhysChemUnitValueWithTemperature 

### ISSUE THREAD

**Issue by thegbom** [esdscom/sdscom-xml#105]
PhysChemUnitValueWithTemperature should extend PhysChemUnitValue and add Temprature. Not having a choice in PhysChemUnitValue  as today. 

It was correct before, but in version 4.2.0, but this has be changed. I have not noticed this before now.

**Comment by dirk-qualisys** [comment]
Do you refer to the change of issue #65 ? The choice is between providing a value and waiving, but hat I do not understand really is that PhysChemUnitValue and PhysChemUnitValueWithTemperature are the same (as are PhysChemValue and PhysChemValueWithTemperature).

Are you saying that we should take Temperature and Pressure out of PhysChemValue and PhysChemUnitValue, and add the in the ...WithTemperate types only?

**Comment by thegbom** [comment]
Yes. I do not under stand the choice in PhysChem... types. PhysChem... types should be be standalone types, where  ...WithTemperate types should inherit these.
