### ISSUE TITLE
IdNoCLInventory obsolete?

### ISSUE THREAD

**Issue by dirk-qualisys** [esdscom/sdscom-xml#108]
The C&L inventory ID is usually not published in safety data sheets. Is there any useful application?

**Comment by dirk-qualisys** [comment]
Propose to delete it since nobody offered insight.

**Comment by Suter-IK** [comment]
We use this number to have create direct links to the C&L inventory, but we don't use it within the SDS

**Comment by dirk-qualisys** [comment]
If you image a company-internal application or a defined company group with specific data exchange requirements, would you consider it useful to keep this value? If so, I will document its purpose. Otherwise, I will delete the field.

**Comment by Suter-IK** [comment]
We don't have any customer using this number internally, nor do we publish it on our SDS.

**Comment by dirk-qualisys** [comment]
I will delete it for lacking use cases then.
