### ISSUE TITLE
New Giscodes

### ISSUE THREAD

**Issue by dirk-qualisys** [esdscom/sdscom-xml#112]
BGBau sent a new list of GISCodes for the German national extension for double-checking and enhancing SDScom.
[MU20161020_Giscodes.xlsx](https://github.com/esdscom/sdscom-xml/files/686993/MU20161020_Giscodes.xlsx)

**Comment by dirk-qualisys** [comment]
Compared to the list of July 2016, this list added 

- GD13: Desinfektionsreiniger, Basis Sauerstoffabspalter, reizend (inklusive schwere Augenschäden)
- GD55: Desinfektionsreiniger, Basis Polyhexamethylenbiguanid
- GS85: Sanitärreiniger, ätzend, mit flüchtigen Säuren

All three are part of SDScom already, but need adding in EuPhraC (which will be done in the next release, 3.0). I don't see a need for action here, but did not check the complete list of GISCodes again.

**Comment by dirk-qualisys** [comment]
Not the end of the story - I compared the Giscodes from the above Excel file 
[Giscode-Excel.txt](https://github.com/esdscom/sdscom-xml/files/1143290/Giscode-Excel.txt)

with the current SDScom implementation
[Giscode-SDScom.txt](https://github.com/esdscom/sdscom-xml/files/1143291/Giscode-SDScom.txt)

which gave me quite a list of differences
[Giscode-Diff.txt](https://github.com/esdscom/sdscom-xml/files/1143315/Giscode-Diff.txt)

Questions:
- What does it mean if we have a Giscode in SDScom and the same with the postfix "ALT" in Excel? Do we have to change SDScom to "ALT", or is the Giscode deprecated and should be deleted from SDScom?
- What is the difference between the status "abgeschlossen" and "ausgemustert" in Excel? If all "ausgemustert" entries are obsolete, the list will become a lot shorter.

**Comment by dirk-qualisys** [comment]
From a phone call with BG Bau today, I got the following info:

1. GISCODEs are prepared by a group of people and not all might follow a common logic for changes. E.g., GD45 was deleted since the SDScom list was derived, but GD25 became GD25_ALT.
2. In some cases, codes were reused: Presumably, D2 became D2_ALT, but a new D2 was introduced. 
3. The status of "ausgemustert" and "abgeschlossen" have no meaning for SDScom in the moment. All those codes are valid and may appear in the market.

**CAUTION: If no. 2 (reusing GISCODEs) is true, this has severe impacts on IT usage**:

- _when referencing the full text by the GISCODE_: software systems must check the meaning and not just the code when printing the GISCODE full text from older data, because the meaning might have changed. In other words: Over time, the GISCODE is not sufficient and the full text or time stamp must be stored with the GISCODE.
- _when using just the GISCODE_: Without a timestamp, you you cannot be sure what the meaning of a GISCODE is.

At a later time, we might have more details on these topics, but this will be past the 4.3 deadline. For now, we will just adopt the latest (Oct. 2016) GISCODE list as-is.

**Comment by QuenzelGISBAU** [comment]
Unfortunatly I missed this issue until now.
We don't think that we have that much of a problem, because the timestamp Dirk referred to is provided by the date of the safety data sheet (IssueDate or RevisionDate).

**Comment by QuenzelGISBAU** [comment]
Because the GISCODE list is changed more often than SDScomXML or at simply at different points in time, we would like to propose changing the data type of the Giscode-Element from GisCodeEnum to string16. 
This of course makes validating the code a lot more complicated but we feel this is needed since we can not always wait for next version of SDScomXML before we use a new GISCODE.

**Comment by dirk-qualisys** [comment]
I think this would have justified a new issue. Anyway, I am not in favor of weakening the constrained data type. Instead I would suggest that we introduce maintenance versions whenever a new GISCODE list is communicated to SDScom, so that the SDScom version number also shows which version of GISCODEs is meant. This also helps with understanding reused GISCODEs correctly. 

Otherwise, we would need a new value with a GISCODE version - which the user might not have as this is normally not communicated with the GISCODEs in the supply chain, so I prefer a solution like "take the newest SDSCom and you will have the newest GISCODEs".

**Comment by Henrich-BGRCI** [comment]
I came accross with a nice article [https://www.ibm.com/developerworks/library/x-extenum/](https://www.ibm.com/developerworks/library/x-extenum/) describing the Problem and giving some Solutions.
Perhaps, in SDSComXMLNE_DE.xsd the DT GisCode could be defined as string16 and restricted by enumeration in an separate XSD (eg. SDSComXMLNE_DE_GISCODE.xsd). The separate XSD could be updated indepentently from the master SDScom release (eg. supplied by an own URL) or could be easily excluded by removing the xs:include statement in SDSComXML.xsd.

**Comment by dirk-qualisys** [comment]
Opened a new issue because closed issues of past releases should not be reopened, to avoid confusion.
