### ISSUE TITLE
UnitIdEnum

### ISSUE THREAD

**Issue by mm-basf-bs** [esdscom/sdscom-xml#114]
Within section 3 at 'DerivedNoEffectLevel' of components there may appear values at 'DnelValue' using unit 'mg/cm2', which not yet has a corresponding enumeration value for 'UnitId'. Can such value be added to 'UnitIdEnum'?

**Comment by dirk-qualisys** [comment]
We do have
			
			
but only
			
The EuphraC phrase mg/cm2 exists since version 2.2, carries the phrase ID 16136203700 and should be added.
