### ISSUE TITLE
ExposureLimitValueTypeEnum

### ISSUE THREAD

**Issue by mm-basf-bs** [esdscom/sdscom-xml#115]
Within SDS section 3 at 'OccupationalExposureLimit' it may appear that companies also use value 'MAKCLV' (regarding guideline 'DFGMAK') or values 'AGWAK' or 'AGWTO' (both regarding guideline 'TRGS 910') which are not yet valid enumeration values for 'LimitValueTypeWithCountryOrOrganisation'.
Can this values be added to 'ExposureLimitValueTypeEnum'?

**Comment by dirk-qualisys** [comment]
I am discussing this with our inhouse experts these days. Is there any official source for the acronyms you suggest, or are these company internal?

More general, I wonder why ExposureLimitValueTypeEnum covers acronyms that refer to one kind of limit value, e.g. STEL = short term, TWA = long term (Limit8H in SDScom), although OccupationalExposureLimit covers both in one instance. I think we need to rework this completely and would like to suggest that we replace this with a country identifier.

**Comment by mm-basf-bs** [comment]
The acronyms we requested are company internal, indeed.

Meanwhile the product safety department of our business partner statet that 'MAKCLV' is not used any longer. For 'AGWAK' and 'AGWTO' they provided the following explanations (both regarding 'TRGS 910').    

'AGWAK' is used for exposure limit values of so called 'Akzeptanzkonzentration'.
The acceptance concentration is a substance-specific quantity.
It is the concentration of a substance in the air at the workplace, which is defined by the risk of acceptance, by the ERB (The ERB of carcinogenic substance describes the correlation between the substance concentration (inhalation) and the statistical probability of the occurrence of cancer.).
Acceptance risk is a cross-material parameter which indicates the statistical probability of the occurrence of a cancer in the amount of 4:10000 or at the latest from 2018 in the amount of 4:100000.

'AGWTO' is used for exposure limit values of so called 'Toleranzkonzentration'.
The tolerance concentration is a substance-specific quantity. 
It is the concentration of a substance in the air at the workplace which corresponds to the tolerance risk via ERB (The ERB of carcinogenic substance describes the correlation between the substance concentration (inhalation) and the statistical probability of the occurrence of cancer.) and is associated with a high, unacceptable risk when exceeded.
Tolerance risk is a cross-material parameter which indicates the statistical probability of the occurrence of cancer in the amount of 4:1000.


As this values are usually different from normal value 'AGW' there is no place to output in SDScom actually.

**Comment by dirk-qualisys** [comment]
> As this values are usually different from normal value 'AGW' there is no place to output in SDScom actually.

That is true, and I hear this is because both are no limit values, i.e. have a purpose that is not covered by the discussed enum. Personally, I tend to reject their addition. Please comment.

**Comment by mm-basf-bs** [comment]
The product safety department of our business partner decided not to use value types 'AGWAK' and 'AGWTO' for SDScom. Issue may be closed.
