### ISSUE TITLE
OccupationalExposureLimit is missing comments for each limit value

### ISSUE THREAD

**Issue by thegbom** [esdscom/sdscom-xml#116]
Sometimes it is required to write a comments together with the limitation value. Today it is not possible.

**Comment by dirk-qualisys** [comment]
The type OccupationalExposureLimit has comments for each instance - but each instance can carry up to two long-term, short-term and ceiling limit values (i.e., up to six values in total per instance).  Do I understand you correctly that you want a comment field per each limit value? Can you provide an example for which the current structure is not god enough (considering that not every remark from the official LV lists need to go into the SDS)?

**Comment by thegbom** [comment]
Say that I got a substance as a component. In OccupationalExposureLimit I would like to state two values. One for dust/spray and one for liquid. How do I state the two in the best possible way? 

I would like to have a short comment where I should write Dust/Spray. Alternatively a enum where it just a set of values.

**Comment by dirk-qualisys** [comment]
My understanding is that the zero to two instances cover the case of having a mg/m³ value, a ppm value, or both. In other words, all limit values in one instance should represent the same OEL. If you have dust and spray limit values, you should use two instances.

If represented that way, would the existing structure be sufficient?

**Comment by thegbom** [comment]
Say that you have two values, like you describe above. How do the reader know which value is dust and spray?

**Comment by dirk-qualisys** [comment]
One entry has the spray value plus comment "Spray", the second has the dust value plus entry "dust".

**Comment by thegbom** [comment]
I do agree

**Comment by dirk-qualisys** [comment]
OK, in this case let's treat this as a documentation issue to be clarified in the specification.
