### ISSUE TITLE
Idea: Create a basic format for phrase catalog

### ISSUE THREAD

**Issue by thegbom** [esdscom/sdscom-xml#117]
Could we agree upon a basic import-format on phrase-catalog using the phrase-types used in sdscomxml? This would be a new xsd containing just this format.

The phrase catalog format should take care of translations, so that all translated merge phrases and phrases could be transferred as one file.

**Comment by thegbom** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
/*
*
* Phrase Catalog format suggested by Torstein Hegbom, 8th April 2017
*
* The suggested format is almost the same as the format descibed in SDSComXML
*
* For translatable sentences, the sentences will have the same PhraseId, but country and language may differ
* 
*/


<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="PhraseCatalogue">
<xs:annotation>
<xs:documentation> The chemical safety datasheet using the included data types. To be filled in... </xs:documentation>
</xs:annotation>
<xs:complexType>
<xs:sequence>

<xs:complexType name="Phrase">
<xs:annotation>
<xs:documentation> Phrase, using optional references to a coordination body assigning ids to all phrases. PhraseId is a unique identifier (primary key) that must exist in each phrase catalogue. PhraseId has precedence over textual phrase values if both are present. PhraseCode is any official or system-internal phrase identifier which may be unique or not (and is often empty). Example: In EuPhraC, PhraseIds 9278174452 to 9278174455 all refer to PhraseCode = H341, however EuPhraC decided to name the other codes as H341.1, H341.2 and H341.3. Note the use of MergePhrase restricts the nesting depth to one level. </xs:documentation>
</xs:annotation>
<xs:sequence>
<xs:element name="PhraseCode" minOccurs="0" type="string64"/>
<xs:element name="FullText" minOccurs="0" type="string1024" maxOccurs="1"/>
<xs:element name="MergePhrase" minOccurs="0" type="MergePhrase" maxOccurs="unbounded"/>

<xs:complexType name="MergePhrase">
<xs:annotation>
<xs:documentation> The MergePhrase's in this file are all included in the phrase-structure, and will not exist alone as a separate structure in the resulting xml file  </xs:documentation>
</xs:annotation>
<xs:sequence>
<xs:element name="MergeText" minOccurs="0" type="string512" maxOccurs="1"/>
<xs:element name="Delimiter" minOccurs="0" type="string3" maxOccurs="1"/>
</xs:sequence>
<xs:attribute name="PhraseId" type="PhraseId"/>
<xs:attribute name="PhraseCatalogueId" type="xs:integer" default="0"/>
<xs:attribute name="MergePhraseNo" type="xs:integer" default="0"/>
<xs:attribute name="ListItemNo" type="xs:integer" default="0"/>
<xs:attribute name="PhraseCountry" type="xs:integer" default="0"/>
<xs:attribute name="PhraseLanguage" type="xs:integer" default="0"/>
<xs:attribute name="CanBeTranslated" type="xs:integer" default="1"/>
</xs:complexType>

</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>`

**Comment by thegbom** [comment]
Please find a proposed structure above. I took the liberty of reopening the issue since it is a missing peice in the SDSComXML-transfer. If you find it a bad idea, please let me know.

**Comment by Henrich-BGRCI** [comment]
Sorry, but I am not sure that I understand the syntax of your given xsd example. Should it be a separate xsd to define an XML file for transfering all phrases of a phrase catalog? Could you provide an example? Following up the question #41 : What is the meaning of ListItemNo and how to define the order of the MergePhrases, which can be necessary to change in translations?

**Comment by thegbom** [comment]
Please find a example below. It describes one sentence for Finish country with merge-phrases:

`<PhraseCatalogue>
<Phrase PhraseId="123" PhraseCatalogueId="ABC123" PhraseCountry="FI" PhraseLanguage="EN" CanBeTranslated="0">
   <PhraseCode>321</PhraseCode>
   <FullText>In Finland they have two languages. Words not alike. Example: [$$1] and [$$2] differ a lot
</Phrase>
<Phrase PhraseId="123" PhraseCatalogueId="ABC123" PhraseCountry="FI" PhraseLanguage="SV" CanBeTranslated="0">
   <PhraseCode>321</PhraseCode>
   <FullText>I Finland har dom två olika språk. Ord är olika. Exempel: [$$1] och [$$2] är mycket olika
</Phrase>
<Phrase PhraseId="123" PhraseCatalogueId="ABC123" PhraseCountry="FI" PhraseLanguage="FI" CanBeTranslated="0">
   <PhraseCode>321</PhraseCode>
   <FullText>Vuonna Suomessa heillä on kaksi kieltä. Sanat ole samanlaisia. Esimerkki: [$$1] ja [$$2] eroavat paljon
</Phrase>
<MergePhrase PhraseId="123" PhraseCatalogueId="ABC123" MergePhraseNo="1" PhraseCountry="FI" PhraseLanguage="EN" CanBeTranslated="1">
   <MergeText>sand</MergeText>
</MergePhrase>
<MergePhrase PhraseId="123" PhraseCatalogueId="ABC123" MergePhraseNo="1" PhraseCountry="FI" PhraseLanguage="EN" CanBeTranslated="1">
   <MergeText>soil</MergeText>
</MergePhrase>
<MergePhrase PhraseId="123" PhraseCatalogueId="ABC123" MergePhraseNo="2" PhraseCountry="FI" PhraseLanguage="SV" CanBeTranslated="1">
   <MergeText>sand</MergeText>
</MergePhrase>
<MergePhrase PhraseId="123" PhraseCatalogueId="ABC123" MergePhraseNo="2" PhraseCountry="FI" PhraseLanguage="SV" CanBeTranslated="1">
   <MergeText>jord</MergeText>
<MergePhrase PhraseId="123" PhraseCatalogueId="ABC123" MergePhraseNo="2" PhraseCountry="FI" PhraseLanguage="FI" CanBeTranslated="1">
   <MergeText>hiekka</MergeText>
</MergePhrase>
<MergePhrase PhraseId="123" PhraseCatalogueId="ABC123" MergePhraseNo="2" PhraseCountry="FI" PhraseLanguage="FI" CanBeTranslated="1">
   <MergeText>maaperä</MergeText>
</MergePhrase>
</PhraseCatalogue>`

**Comment by thegbom** [comment]
In order to succeed in sentence import, we need a relation between xml tags and phrase-id. Below I have made a spreadsheet that shows the a numeric identification of each tag.  
[xml_relations.xlsx](https://github.com/esdscom/sdscom-xml/files/1185503/xml_relations.xlsx)

Using this we can create a phrase-import-relation xml-file. This will enable the exporter to tell the importer what tag-id's that can use one specific phrase-id.

**Comment by thegbom** [comment]
This means that the format mentioned above needs to have a new attribute on the Phrase element - AppliesTo. This attribute will contain a comma separated list of tag_id. As shown in the example attached
[example2.txt](https://github.com/esdscom/sdscom-xml/files/1185956/example2.txt)

**Comment by dirk-qualisys** [comment]
I agree that a phrase-field assignment is necessary or at least helpful. 

EuPhraC is currently addressing this by adding XPATH information to the phrase library, i.e. each phrase (identified by its EuPhraC ID) can have mutliple occurrences in the SDS (represented by a structure code and, in future, the respective XPATH info). Thus for the combination of EuPhraC and SDScom, the issue will be solved and the XSD proposal is basically a new/revised data format.

As SDScom is independent from phrase catalogues, and your proposal is ultimately independent from SDScom, this is more an entirely new, albeit small project for any phrase catalogue transmission and should be treated and maintained accordingly.

Did you aim at just adding field/usage info to EuPhrac, in which case we might close this issue, or aim at a standardized phrase catalogue exchange format, in which case I would like to discuss this in the next workshop and implenet it separately, if agreed?

**Comment by thegbom** [comment]
The future for SDScom is EuPhraC, I feel no doubt about that.  For now the company I represent, EcoOnline, requires to have non-EuPhraC-catalogs. Having that in mind, I would like to see a standardized phrase catalogue exchange format. I agree, it would be a good place to discuss this in the next wokshop. And yes, it should be developed separately, but closely linked to SDScom.

**Comment by dirk-qualisys** [comment]
Long time since this discussion started... The steering committee discussed this today together with issue #210. Because there are licensing issues with the exchange of complete phrase catalogues, and SDScom will have the option of submitting multiple translations for the same phrase in the same XML file, the project will not maintain a separate format for phrase library exchange.

But I still agree that the future of SDScom is EuPhraC :)
