### ISSUE TITLE
AdrTunnelRestrictionCode should be a string

### ISSUE THREAD

**Issue by dirk-qualisys** [esdscom/sdscom-xml#12]
Is currently a phrase field, but will never need translation.

**Comment by nils-eska** [comment]
This issue will be handled within the next Version. There are some more fields in section 14 which have a different focus than phrase.

**Comment by dirk-qualisys** [comment]
Cannot be closed until either solved or declined

**Comment by dirk-qualisys** [comment]
Nils, please define which fields should be changed.

**Comment by dirk-qualisys** [comment]
Please comment if we should fix this in V4..

The advantage is that every Tunnel Restriction Code creates a user phrase currently, which would be avoided by a string. The disadvantage is the imcompatibility with V4.2.0 if we fix.
