### ISSUE TITLE
DOT transportation data and other regional legislation (scope!)

### ISSUE THREAD

**Issue by dirk-qualisys** [esdscom/sdscom-xml#126]
As per customer request, we need to integrate DOT information with SDScom data.

If this would be all, it is certainly easy to add to section 14. But it basically opens the field for other national US regulations in section 15 and 8, and ultimately for other classification data. Thus this request revives the discussion on widening the scope to non-EU countries. How should we handle this? Just add DOT for the moment, or add classification data and US national regulations as well?

_(This is part of a company-internal IT integration project, so the context may ultimately lead to the product data record as foreseen for version 5, instead of a document data record. For the near future, the document approach is sufficient.)_

**Comment by Henrich-BGRCI** [comment]
I am not familiar with DOT or ther US national regulations, but in general for national regulations there are the national extensions, which can be may extended to non-EU countries. Here, a user could use several national extensions simultaneously.
I think, in the core schema definitions the data fields and their allowed values should be restricted only to those in agreement to CLP.

**Comment by dirk-qualisys** [comment]
On a more general level, this issue is relevant for a lot of other topics as well: GISCODES should go in section 7, waste key numbers in section 13, other region's classification in section 2 etc. If we would introduce "region nodes" to mark data which is valid only for limited regions, this could become a concept for transmitting worldwide data in one set. This implies dropping the national extensions in their current form. To be discussed!

**Comment by dirk-qualisys** [comment]
Workshop on 12. October 2017 said:

- National extensions are not the right place because DOT is for USA, and a European SDS does not (usefully) have any national regulations for the U.S.
- Extending the transport section would still violate the idea of transferring not more than the SDS content via XML, which is considered essential for SDScom acceptance at least for the near future.

**Comment by dirk-qualisys** [comment]
Steering Committee decided not to add DOT information to SDScom currently. This is currently driven only by company-internal data exchange projects and thus can be covered otherwise, so that the overall acceptance of SDScom has a higher priority.
