### ISSUE TITLE
ProductIdentity/Synonym lacks structure

### ISSUE THREAD

**Issue by dirk-qualisys** [esdscom/sdscom-xml#134]
TradeName in section 1 is only allowed for mixtures, so should be in a "choice" structure together with SubstanceName, which should be the same structure as in section 3 (with IUPAC, INCI, ....)

**Comment by dirk-qualisys** [comment]
Defined new type SubstanceName which is now used in sections 1 and 3.

**Comment by Henrich-BGRCI** [comment]
According to EU 2020/878 (1.1 "... Other names or synonyms by which the substance or mixture is labelled or commonly known may be provided. ...") and CLP Art. 18 2. and 3. ("shall consist of at least the following"), it is possible to state substance/mixture names, synonyms as well as trade names; therefore, the mandatory choice between SubstanceName and TradeName should be discard and changed to former version that both can given at the same time.

**Comment by dirk-qualisys** [comment]
For compatibility reasons, I kept the current structure and just removed the choice. You could of course argue that at least the ProductIdentifiers tag is now superfluous, but the the UFI would have to move towards the end of TradeProductIdentity according to the rule that RegionXX tags should come at the end of each (sub)structure. So, the now implemented structure is fully backwards compatible.
