### ISSUE TITLE
Phrase type: phraseId attribute is of type string16

### ISSUE THREAD

**Issue by dlichtenberger-chemdox** [esdscom/sdscom-xml#16]
When exporting SDBs that are based on the CHEMDOX phrase catalog we run into issues with the phraseId attribute: our phrase IDs are usually longer than 16 characters, so we have to cut off the phrase ID in order to generate a valid XML document.

Is it possible to relax the length constraint on the phraseId attribute of Phrase elements (e.g. use string256 instead of string16)?

**Comment by dirk-qualisys** [comment]
256 characters seems a long shot for a useful ID, but I agree that the length should be at least the length of a UUID. Which length would Chemdox need?

**Comment by dlichtenberger-chemdox** [comment]
Technically we would support 250 characters in a key, but I agree that this is too much in a useful scheme. In practice our keys are less than 50 characters, so string64 or string128 would be fine.

**Comment by dirk-qualisys** [comment]
Chose string128 to be on the safe side, and implemented this as a new, separate type "PhraseId". Assigned all elements "PhraseId" to this new type to ensure consistency in case of future changes.
