### ISSUE TITLE
IndexNo should allow also alphanumeric characters

### ISSUE THREAD

**Issue by Henrich-BGRCI** [esdscom/sdscom-xml#17]
In the Summary of Classification and Labelling of the ECHA, the Index Number contains often the character 'X' the last position (after the third hyphen). According to the XSD the simple datatyp IndexNo allows only digits and hyphens but no alphabetic characters as required here.

**Comment by dirk-qualisys** [comment]
Correct - pattern should be [0-9]{3}-[0-9]{3}-[0-9]{2}-[0-9,X]
