### ISSUE TITLE
ReachRoleDescriptionEnum

### ISSUE THREAD

**Issue by Henrich-BGRCI** [esdscom/sdscom-xml#178]
In SupplierInformation/Role the RoleCode and ReachRole are defined. What is the difference between both (see also #18)? 
RoleCode is using RoleDescriptionEnum, which is not defined. Just RoleDescriptionEnum is defined.

**Comment by dirk-qualisys** [comment]
As described in the issue #18 that you correctly refer to, RoleDescriptionEnum is maintained for compatibility to Norwegian applications, while ReachRoleDescriptionEnum is defined according to REACH needs. Both are well defined as far as I can see.
