### ISSUE TITLE
RoleDescriptionEnum definition

### ISSUE THREAD

**Issue by dirk-qualisys** [esdscom/sdscom-xml#18]
Two questions:

* Why are manufacturers split into "Manufacturer" (presumably within the EU only) and "Foreign Manufacturer"? If the manufacturer is non-EU, there must be an Only Representative. Since the location can be determined from the address, I cannot see the use of this difference.

* What is the difference between "Responsible company", "National responsible" and "Only Representative"? It seems that many cases would match more than one role, which makes the role definition ambiguous.

Please clarify.

**Comment by nils-eska** [comment]
These two options was introduced by the Norwegian working Group to be compatible with the former Norwegian Format. From my Point of view, the entry "Foreign Manufacturer" can be discarded.

Also these options has been introduced by the norwegian working group. If these three fields causes any ambiguity, please fell free to make a proposal for a better identification of the Supplier Information

**Comment by dirk-qualisys** [comment]
My best bet as of today, based on the roles defined in REACH:
- Manufacturer
- Importer
- Only Representative [= legal representative of non-EU companies within the EU] 
- Distributor [including national representatives of a manufacturer or importer]

IMHO, we should remove 
- "Responsible company" and "National responsible", as these are no legal role and mostly a distributor.
- "Reimporter" as there is almost no way to guarantee the reimported product remained unchanged, and a reimport is an import in fact.
- "Formulator": Interesting question. I propose to drop it as a formulator is a manufacturer (of a mixture), but OTOH this is a nice analogy to the exposure scenario titles "roles".
- "Foreign manufacturer" = manufacturer from a country other than the locale of the safety data sheet.
- "Downstream user" is nobody who usually issues a safety data sheet.

Please comment.

Do we need compatibility to Norwegian activities in V5 of SDScom? Can we ask somebody there about their reasoning?
-

**Comment by dirk-qualisys** [comment]
Sorry, no clue how I create the bold font :-/

**Comment by dirk-qualisys** [comment]
As discussed in Hamburg on the 19. of November, it might be best to leave the current data type unmodifed, annotate it as Norwegian role definition and add a ReachRoleDescriptionEnum with the four roles under REACH. Thus relabeled as enhancement for V4.
