### ISSUE TITLE
Make OtherTransportInformation consistent

### ISSUE THREAD

**Issue by dirk-qualisys** [esdscom/sdscom-xml#185]
As a follow-up to issue #170 and #171, the "other information" should list LQ, EQ, and special provisions for all carriers. Data should not be phrases if it does not need translation.

**Comment by nils-eska** [comment]
Are the fields AdrRidExceptedQty, AdnExceptedQty, ImdgExceptedQty and ImdgEmsCode really relevant within an SDS?

**Comment by dirk-qualisys** [comment]
EQ values have the same relevance as LQ values - they ease the transport for smaller quantities (although certainly in a different way). Our users explicitly asked for it when EQ values were introduced.

I took the EmS code from the previous definition of SDScom - that is not a reason, but an explation only ;) I remember that we had a small but significant group of users that have asked for it before we introduced it in our software, but as there are no complaints now, I can't say if users would miss it if it was dropped. As a deletion would be a reduction of transmittable content, I would still maintain it in SDScom.

**Comment by dirk-qualisys** [comment]
From the workshop today: Several participants voted for keeping it in the structure, in order to document company internal assessments in the SDS as the one comprehensive document of reference. This is certainly beyond the legal requirements on SDS, but if processes are defined correctly and the author of information is trustworthy, this info is considered helpful. Actors in the supply chain who do not want to use this info may ignore it during import.

**General rule of reference for future cases:** If there are users and applications for the data, it should be included as optional fields. SDScom will not restrict the XML document to the bare necessities of law, but provide a structured approach for submission of as much safety related data as possible.
