### ISSUE TITLE
Support for UFIs

### ISSUE THREAD

**Issue by dlichtenberger-chemdox** [esdscom/sdscom-xml#187]
As we are in the process of improving UFI support in CHEMDOX, we did not find a place in SDSComXML where we would actually put the UFI if it was printed in an SDS (except generic fields like "productNo"). I noticed that there are open issues to integrate (parts of) the Article 45 notification, however as a first step adding UFIs to IdentificationSubstPrep or ProductIdentity might already be a big step forward.

**Comment by dirk-qualisys** [comment]
Indeed, this relates to issue #124 . I will push this so that there is an addition soon, and am happy if you could check the requirements analysis there. Thanks for bringing this up in time!
