### ISSUE TITLE
SDStransfer Workshop 11th October 2018

### ISSUE THREAD

**Issue by Henrich-BGRCI** [esdscom/sdscom-xml#189]
The next SDStransfer Workshop will be on October 11th 2018 in Heidelberg. The workshop will tackle programming issues regarding SDScomXML and SDBtransfer as well as future perspectives of SDScomXML.
For further Information and resgistration, please, see https://www.sdbtransfer.de/anmeldung/

**Comment by Henrich-BGRCI** [comment]
Attention! The SDBtransfer IT-Workshop is postponed to 28th February 2019. Currently, he agenda is under revision and will be published in January.

**Comment by dirk-qualisys** [comment]
Not an issue, but an announcement. Thus closed.
