### ISSUE TITLE
Refactor SDScom for easier implementation

### ISSUE THREAD

**Issue by dirk-qualisys** [esdscom/sdscom-xml#191]
1. The national extensions are largely unused and, with today's issue tracking, easier maintained in one of the other files (or one file for national extensions). 
2. Looking at a closer collaboration with ESCom, the Phrase type should be renamed to avoid naming conflicts.
3. More parts of the XML tree should be specified als types, not elements, to allow easier reusing of specification parts.

All of these changes do **not** change the validity of XML files, i.e. they only change the way of defining the schema.

**Comment by Suter-IK** [comment]
1. I would prefer one separate file for national extensions.
2. type="Phrase" is widely used within the current schema, but not within the xml as tag. Generally I agree, but why do you expect naming conflicts?
3. Which one do you have in mind?

**Comment by dirk-qualisys** [comment]
1. Agreed, one file for national aspects is easier to read than an integration into the main schema file.
2. Doing exercises with combined ESCom/SDScom schemas, I always have to rename either ESCom's or SDScom's Phrase type, which is the only naming conflict. In preparation of any type of combined data format, or for companies that implement both standards in the same environment, avoiding any potential conflict reduces debugging time.
3. Firstly, I would consistently form a type definition for <InformationFromExportingSystem>, in the way that ExposureControlPersonalProtection, PhysicalChemicalProperties, ToxicologicalInformation and EcologicalInformation were defined in 4.3.1 already and all other SDS sections are defined in the current draft for 4.4.0. As a next and more important step, I would like to isolate all parts in types of their own which cover national or European legislation (as opposed to GHS-based data which is likely valid worldwide). This helps to work on enhancements for international use, as decided by the steering committee.

**Comment by Henrich-BGRCI** [comment]
I favour separate files for the national extensions, too, because it is easier to read. And, even more important, if updates are needed in the national extensions (e.g., GisCodes), the rest needn't to be changed.

I strongly disfavour a renaming of SDScom's datatype Phrase. A renaming of this widely used datatype cannot be communicate to those users, not needing ESCom but just SDScom. Am I right in thinking that using different namespaces there is no name conflict using the same datatype name in different XSD?

How many changes are needed for interface implementation, if the other sections are also changed to type definition?

**Comment by dirk-qualisys** [comment]
There might be misunderstandings here:

- The current setup with many files, one for each national extension and almost all being empty, has negative impact on readability and maintenance. With the same functional power, we can reduce this to one file for all negative extensions.
- Renaming Phrase does not need to be communicated for users. It's like renaming a variable in a software - the user won't see this name and can work with the same data. The use of namespaces in SDSComXML.xsd would change basically every reference to a datatype, so is harder to read than using "PhraseWithParam" instead of "Phrase"
- Forming elements into types would also be invisible to the end user and without change to the XML data files, as I mentioned initially. As this is part of a process to differentiate between GHS and EU specific content, I do not have an assessment yet.

As your remarks, Mr. Henrich, aim at user experience and readability, I think the proposed changes still fulfil your requirements.

**Comment by Henrich-BGRCI** [comment]
Sorry incorrect wording: With user I did not mean the end user but the programmer using SDScom.  In my opinion, at the moment there is dwindling acceptance on the part of software companies to do any major changes.

**Comment by dirk-qualisys** [comment]
Rethinking the different arguments, I will apply a change as follows: 
* All the empty national extensions are collected in one file, but the extensions for DE and NO are kept separately for better reading. This is a "mixed approach" from the discussed pro's and con's.
* I applied a namespace to SDScom, just as ESCom does. This fulfils the same purpose as renaming Phrase, so this name stays the same, just as Mr. Henrich proposed. This approach is cleaner and provides more flexibility for schema handling, but changes the root tag from 

`<DatasheetFeed xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="SDSComXML.xsd">`

to

`<SDScom:DatasheetFeed xmlns:SDScom="http://www.esdscom.eu/SDScom" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.esdscom.eu/SDScom SDSComXML.xsd">`

Other than that, XML data files should still be fully compatible with the latest status. Please check it out and let me know what you think.
