### ISSUE TITLE
XML Naming Rules not following standard?

### ISSUE THREAD

**Issue by Suter-IK** [esdscom/sdscom-xml#197]
https://www.w3schools.com/xml/xml_elements.asp states the following: 
XML elements must follow these naming rules:

- Element names are case-sensitive
- Element names must start with a letter or underscore
- `**Element names cannot start with the letters xml (or XML, or Xml, etc)**`
- Element names can contain letters, digits, hyphens, underscores, and periods
- Element names cannot contain spaces

We have the elements «XmlStandardVersionNo» and «XmlStandardSubset» which do not follow the standard XML rules. How can we fix this? 
I suggest to replace the elements by «StandardVersionNo» and «StandardSubset» but how can we maintain backwards compatiblity? 
A feedback from a customer was the following: 
> Das SAP PO hält sich offensichtlich an diese Konvention und kann nach dem Import der Definition die darin enthaltene Nachricht nicht lesen.

**Comment by dirk-qualisys** [comment]
It's a bug and we must fix it, but as this did not seem to create problems in most applications, I suggest not to revise V4.4.0 for this.

**Comment by dirk-qualisys** [comment]
Since "Standard" can be ambigous, I will rename to "SdscomVersionNo" and "SdscomSubset".
