### ISSUE TITLE
Swiss storage class

### ISSUE THREAD

**Issue by Suter-IK** [esdscom/sdscom-xml#198]
The Swiss storage class has a different enumeration than the German Lagerklasse.
[Leitfaden_Lagerung_2018_Bildschirmversion.pdf](https://github.com/esdscom/sdscom-xml/files/2694991/Leitfaden_Lagerung_2018_Bildschirmversion.pdf)
Source: https://www.kvu.ch/de/arbeitsgruppen?id=151

Therefore I suggest to update the Switzerland XSD like this: 
[SDSComXMLNE_CH.xsd.txt](https://github.com/esdscom/sdscom-xml/files/2694993/SDSComXMLNE_CH.xsd.txt)

Thank you for your highly appreciated assistance.

**Comment by dirk-qualisys** [comment]
Did some editing on your proposal, for naming consistency. Plus renaming of fields in the German extension because now "StorageClass" needs proper differentiation between CH and DE. Please review.

**Comment by dirk-qualisys** [comment]
There is another inconsistency bewteen the Swiss and German storage class: All German values are preceded with "LGK", the Swiss values are not (probably because there is no multilingual acronym that could be used). 
a) Should that stay inconsistent?
b) Should we delete "LGK" from the German storage class?
c) Is there any non--translatable appropriate acronym for Switzerland that should be used?

**Comment by Suter-IK** [comment]
Thank you for reviewing. 
a) German acronym in Switzerland is LK, where French acronym couldn't be found yet, but surely will be different (thinking at GHS symbols which also differs: GHS01 vs SGH01 in French)
b) I don't have a problem with it, but it might be considered as an overdetermination: Field is Storage class, content is "LGK xx"
c) no, because "LK" is widely used whereas French will be different.

**Comment by Suter-IK** [comment]
Found the Italian text: **Classe di stoccaggio (CS)**   [>Source](https://m4.ti.ch/fileadmin/DT/temi/prodotti_chimici/documenti/Stoccaggio_sostanze_pericolose_Guida.pdf)
![unbenannt_i](https://user-images.githubusercontent.com/16387831/50274729-35497200-043e-11e9-9952-8b3b1e4b90c2.png)

and French text: **Classe d’entreposage CE**  [>Source](https://extranet.kvu.ch/files/documentdownload/180823115816_Lagerung_gefaehrlicher_Stoffe_fr_web.pdf)
![unbenannt_fr](https://user-images.githubusercontent.com/16387831/50275081-e6e8a300-043e-11e9-8af1-69e335d2df74.png)

**Comment by dirk-qualisys** [comment]
As the consistency between the German and Swiss storage class representation is achieved in version 5 and the prefix "LGK"/"LK"/"CE"/"CS" may be viewed as a title or header for the actual class (which is then not part of SDScom), no further action is necessary and this issue can be closed.
