### ISSUE TITLE
Difference between PhraseCode and PhraseId?

### ISSUE THREAD

**Issue by Henrich-BGRCI** [esdscom/sdscom-xml#20]
In the complexType "Phrase", what is the difference between the element "PhraseCode" type="string64" and the attribute "PhraseId" type="string16"?

**Comment by dirk-qualisys** [comment]
PhraseCode is any official or system-internal phrase identifier which may be unique or not (and may be present or not). PhraseId is a unique identifier that must exist in each phrase catalogue. Example: In EuPhraC, PhraseIds 9278174452 to 9278174455 all refer to PhraseCode = H341, however EuPhraC decided to name the other codes as H341.1, H341.2 and H341.3.

I think the documentation needs an enhancement here.
