### ISSUE TITLE
Link to sdscomxml4.2.0.xsd not working

### ISSUE THREAD

**Issue by Henrich-BGRCI** [esdscom/sdscom-xml#21]
The links to the XSD-files of SDScomXML version 4.2.0 are not working: http://www.sdscomxml.eu/sdscomxml4.2.0.xsd

The links to the old XSD-files are working:
http://www.sdscomxml.eu/sdscomxml4.0.3.xsd
http://www.sdscomxml.eu/sdscomxmldt4.0.3.xsd
http://www.sdscomxml.eu/sdscomxmlct4.0.3.xsd

The XSD for the national extension includes still the old XSD of version 4.0.3. Here, of each SDScomXML version a separate national extension file is needed:
http://www.sdscomxml.eu/sdscomxmlne_de.xsd

**Comment by nils-eska** [comment]
The Link to the XSD-File is now http://www.sdscomxml.eu/420/sdscomxml4.2.0.xsd

The Version 4.0.3 is still available under http://www.sdscomxml.eu/sdscomxml4.0.3.xsd and under http://www.sdscomxml.eu/403/sdscomxml4.0.3.xsd as well.

**Comment by dirk-qualisys** [comment]
Mr Henrich, where did you take the wrong link from?

**Comment by dirk-qualisys** [comment]
As per clarification of Mr Henrich, the wrong link was constructed based on the structure of the old one, and there is no broken link on the web or in documentation.

**Comment by Suter-IK** [comment]
Where do you publish the current and future links for those files?
Neither http://www.sdscomxml.eu/sdscomxml4.2.1.xsd nor 
http://www.sdscomxml.eu/421/sdscomxml4.2.1.xsd are working (manually edited)
I'm using this value for to the "noNamespaceSchemaLocation" attribute in the XML file.

**Comment by nils-eska** [comment]
Due to compatibility reasons, the Version 4.2.1 is available under:

http://www.sdscomxml.eu/421/sdscomxml.xsd

From now on, the format of the online publishing directory will be always
http://www.sdscomxml.eu/XXXX/sdscomxml.xsd.
XXXX= Version number with the maximum of for digits
