### ISSUE TITLE
Problems with Namespace

### ISSUE THREAD

**Issue by Henrich-BGRCI** [esdscom/sdscom-xml#214]
With the change from version 4.2.1 to 4.4.0.1 I have problems in setting up a valid XML file. Validating the following code against the XSD of 4.4.0.1 (using Notepad++/XML Tools) I get the error message:
`ERROR: Element 'DatasheetFeed': No matching global declaration available for the validation root.`

The used code:
```
<?xml version="1.0"?>
<DatasheetFeed xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SDScom="http://www.esdscom.eu/SDScom" xsi:schemaLocation="./4401/SDSComXML.xsd">
  <datasheet>
  <!-- content -->
  </datasheet>
</DatasheetFeed>

```
How do I define the correct namespace? Can anybody supply me a valid example XML file?

The main differences between in the XSD of vers. 4.2.1 and 4.4.0.1, what I can see, are the complexType definition inside and outside the element "DatasheetFeed", respectively:
vers. 4.2.1: 
```
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:include schemaLocation="SDSComXMLDT.xsd"/>
...
<xs:element name="DatasheetFeed">
...
<xs:complexType> 
...
</xs:complexType>
</xs:element>
</xs:schema>
```

vers. 4.4.0.1: 
```
<xs:schema targetNamespace="http://www.esdscom.eu/SDScom" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:SDScom="http://www.esdscom.eu/SDScom" xmlns:xs="http://www.w3.org/2001/XMLSchema" version="2.0">
<xs:include schemaLocation="SDSComXMLDT.xsd"/>
<xs:include schemaLocation="SDSComXMLCT.xsd"/>
<xs:complexType name="IdentificationSubstPrep">
...
<xs:element name="DatasheetFeed">
...
<xs:complexType>
...
</xs:complexType>
</xs:element>
</xs:schema>
```

**Comment by dirk-qualisys** [comment]
Applying namespaces is actually the result of a discussion about combined use of ESCom an SDScom - see your comment at https://github.com/esdscom/sdscom-xml/issues/191#issuecomment-427274618 , which is followed by a commit which refactored SDScom to use an explicit namespace. The XML should now read as follows:

```
<?xml version="1.0" encoding="UTF-8"?>
<SDScom:DatasheetFeed xmlns:SDScom="http://www.esdscom.eu/SDScom" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.esdscom.eu/SDScom file:/F:/GitHub/sdscom-xml-4_4_0/SDSComXML.xsd">
    <Datasheet>
        <InformationFromExportingSystem>
        ...
```

So, the header is slightly different to introduce the namespace SDScom, which is then used in the outermost tag SDScom:DatasheetFeed. All the rest remains unchanged.
I hope this helps.

**Comment by Henrich-BGRCI** [comment]
Thanks a lot. Notepad++ can now validate the XML file.
