### ISSUE TITLE
TransportClassEnum

### ISSUE THREAD

**Issue by joern-epos** [esdscom/sdscom-xml#217]
The TransportClassEnum in Version 4.4.0 is not defined correctly. Class 2 is missing, class 1 is defined twice. The second class 1 should be 11 because his XMLName is 1.1. 

Because the enumeration is also used by the 'HazardLabel'elements also the classes 1.4, 2.1, 2.2 should be added.

**Comment by dirk-qualisys** [comment]
Can we change the type name from HazardLabelEnum to TransportHazardLabelEnum? Hazard labels are also used under GHS so that HazardLabelEnum is ambiguous.

**Comment by dirk-qualisys** [comment]
Regarding 9A, I have looked at the original transport carrier lists and (with my limited knowledge on hazardous goods transport) found the following:

- IATA-DGR does not use a numeric hazard label, but words like "Corrosive" or "Explosive". While some UN numbers show "Explosive" which denotes the class only, other are more specific with "Explosive 1.4". I think we need to change this to a phrase type (plus add such labelling phrases in EuPhraC). Of course that can't go into 4.4.0.1 as it is a refactoring which is not backwards compatible, but would be good for 5.0.
- IMDG does not have hazard labels at all, but compiles them from class and subrisk. Drop it in 5.0?
- ADR as well as ADN use 9A, 7X and 7E in addition to the list above.
- RID adds 9A, 7E, 7X, 13 and 15 to the list.

I propose this implementation:

	<xs:simpleType name="TransportHazardLabelAdrAdnOnlyEnum">
		<xs:annotation>
			<xs:documentation>List of carrier specific hazard label elements for ADR.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="string">
			<xs:enumeration value="7E"/>
			<xs:enumeration value="7X"/>
			<xs:enumeration value="9A"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="TransportHazardLabelAdrAdnEnum">
		<xs:union memberTypes="SDScom:TransportHazardLabelEnum SDScom:TransportHazardLabelAdrAdnOnlyEnum"/>
	</xs:simpleType>
	<xs:simpleType name="TransportHazardLabelRidOnlyEnum">
		<xs:annotation>
			<xs:documentation>List of carrier specific hazard label elements for RID.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="string">
			<xs:enumeration value="7E"/>
			<xs:enumeration value="7X"/>
			<xs:enumeration value="9A"/>
			<xs:enumeration value="13"/>
			<xs:enumeration value="15"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="TransportHazardLabelRidEnum">
		<xs:union memberTypes="SDScom:TransportHazardLabelEnum SDScom:TransportHazardLabelRidOnlyEnum"/>
	</xs:simpleType>

Further types like this are necessary for the USA.

**Comment by joern-epos** [comment]
In the branch for 4.4.0.1 the necessary changes added. Can we use that version or is a official release planned?

**Comment by nils-eska** [comment]
Yes, you can use the branch 4.4.0.1
If further modifications for the 4.4.x.x will be needed in future, we will create a new branch 4.4.0.2.
The next offical master release will be the 5.0

**Comment by dirk-qualisys** [comment]
Not merged, and 4.4.0 is now beyond the maintenance period.
