### ISSUE TITLE
DoseEnum

### ISSUE THREAD

**Issue by Henrich-BGRCI** [esdscom/sdscom-xml#22]
In the simpleType "DoseEnum",  the following list elements have incorrectly an 'o' instead of '0':
<xs:enumeration value="LClo"/>
<xs:enumeration value="LDlo"/>
<xs:enumeration value="ERClo"/>

**Comment by dirk-qualisys** [comment]
I think you mean LDlo, LClo, ERClo. These should be LDLo, LCLo, ERCLo (with an uppercase L in the middle), but the o is correct.

**Comment by dirk-qualisys** [comment]
After consultiation with Nils, the above list elements will be added to maintain compatibility. In SDScom version 5, the elements with wrong spelling will be deleted.

**Comment by dirk-qualisys** [comment]
More items missing: 
* EL10 (Effect level; Loading rate, invertebrates, chronic; test with water accomodated fraction, testingof poorly soluble substances)
* EL50 (invertebrates, acute)
* IC50 (Inhibitory concentration; only for algae, analog to EC50)
* LL50 (fish, analog to EL50

**Comment by Henrich-BGRCI** [comment]
As we discussed at the workshop in Hamburg, the enumeration should contain an entry like "others" to make it possible to give values like "LD10" even if they cannot be used directly deriving the classification.

**Comment by dirk-qualisys** [comment]
Have raised this to the EuPhraC group for validation and coordination. IC50 is confirmed necessary, other types are most likely inappropriate because not directly relevant for GHS/CLP classification. Will enhance DoseEnum with "IC50" and "other", but leave this issue open for final confirmation.
