### ISSUE TITLE
ReachRegNo lower case X

### ISSUE THREAD

**Issue by QuenzelGISBAU** [esdscom/sdscom-xml#24]
The type ReachRegNo should allow lower case x, since they are fairly common in SDSs. Ergo the pattern should be [0-9]{2}-[0-9]{10}-[0-9]{2}(-[0-9,X**x**]{4})?

**Comment by dirk-qualisys** [comment]
Use pattern \d{2}-\d{10}-\d{2}(-\d{4}|-xxxx|-XXXX)? to ensure that the last block covers either digits or lowercase x or uppercase X, but no arbitrary mix.
