### ISSUE TITLE
complexType name="PercentageValue"

### ISSUE THREAD

**Issue by Henrich-BGRCI** [esdscom/sdscom-xml#25]
What is the reason for defining the datatype "PercentageValue", which in extension based on "Value" but without any further addtions or restrictions? The type is used e.g. in 15.1.1.6.1 VocInPercentByWeight.

**Comment by QuenzelGISBAU** [comment]
I agree with you that this is not necessary but I somewhat like the approach used now. For me "Value" is something like an abstract type of which the used types only inherit but which is never used to carry data itself.

**Comment by dirk-qualisys** [comment]
My understanding is that this is basically a UnitValue with a fixed unit "%". Should be added in the annotation.
