### ISSUE TITLE
PackingGroupComments is not unbounded

### ISSUE THREAD

**Issue by dlichtenberger-chemdox** [esdscom/sdscom-xml#27]
In SDSComXML 4.2.0, PackingGroupComments (14.5.4) is 0..n according to SDSComXmlStandard.xlsx but is not marked as unbounded in the schema definition.

**Comment by nils-eska** [comment]
Ok, this have to be fixed in the next Version.

**Comment by dirk-qualisys** [comment]
Was fixed by Nils in commit 384cd9adffdcd235a9edc2bc3dd3e502fdd528d0
