### ISSUE TITLE
Form and Physical State

### ISSUE THREAD

**Issue by kderhan** [esdscom/sdscom-xml#273]
Are form and physical state (Aggregatzustand etc.) differentiated in SDSComXML, or are all the details assigned to the form element?
Thank you for your support.

**Comment by dirk-qualisys** [comment]
Yes, they are different types. Have a look here:
![grafik](https://github.com/user-attachments/assets/79616118-6265-4d57-8775-1b9735864256)

**Comment by kderhan** [comment]
Thx
