### ISSUE TITLE
StorageClassEnum: class 4.2A instead of 4.2

### ISSUE THREAD

**Issue by dlichtenberger-chemdox** [esdscom/sdscom-xml#29]
At least according to https://de.wikipedia.org/wiki/Lagerklasse, no storage class 4.2A exists (only 4.2 without a suffix).

**Comment by dirk-qualisys** [comment]
Correct. Even in the latest edition of TRGS 510, there is a flaw in annex 4 ("Anlage 4 zu TRGS 510:
Vorgehensweise zur Festlegung der Lagerklassen (Zuordnungsleitfaden)" - the list of descriptions of storage classes refers to 4.2A (but no 4.2B) while all other parts refer to 4.2, without a letter.
