### ISSUE TITLE
StorageClassEnum: how to map class 10-13?

### ISSUE THREAD

**Issue by dlichtenberger-chemdox** [esdscom/sdscom-xml#30]
How should substances with a LGK classification of "10-13" be exported? It would be possible to add all individual classes (10, 11, 12, 13), which also happens to match the maximum number of entries  (maxOccurs) in the schema. Is this the desired export mapping?

**Comment by nils-eska** [comment]
The LGK should be clearly determined in the SDS to one class regarding TRGS 510.

**Comment by Henrich-BGRCI** [comment]
Yes, it is intended to add the invididual classes (10, 11, 12, 13) to  describe LGK 10-13; therefore, the maxOccurs is 4.

**Comment by dlichtenberger-chemdox** [comment]
Thanks!
