### ISSUE TITLE
Multi-component products

### ISSUE THREAD

**Issue by QuenzelGISBAU** [esdscom/sdscom-xml#32]
A lot of chemical products are to be used with one or more specific component (e.g. epoxy resins and hardener). 
SDSComXML should have a way to communicate these components and maybe the percentages of each in the final mixture.
In addition to the trade name of the components we also need the "ProduktstammID" thus a corresponding field (maxOccur =1 Type: string:64) for this is also needed.

**Comment by dirk-qualisys** [comment]
You may be referring to two different cases:

1. Products that form part of a set or kit: The set or kit can be refereced similar to other trade names, probably with a marker to identify that this product is "part of" (as opposed to "identical with") <trade name>, but is a percentage useful in this case? The product stay separate, and any mixing percentage during application is not part of the SDS, at least not in a structured way.
2. Products that are used as intermediates, i.e. that form part of a multi-level composition. Usually the itermediate manufacturer will not know the percentage, or this percentage may vary depending on the end product.

As I fail to see a compatible solution for case 2, I propose to solve this in v5. CLP article 45 notifications will support multi-level compositions, so we should do the same. The ProduktStammID is pretty much the same as the UFI (Unique Formula Identifier). But this only works for the end product SDS, not the intermediate SDS. Is that sufficient or did I misunderstand your issue?

For case 1, I propose to enhance v4 with a boolean field "PartOfSet" in ProductIdentity. OK?

**Comment by QuenzelGISBAU** [comment]
I was referring to case 1. A boolean field is better than nothing but we would like to have the possibility to reference at least a trade name and even better another ID. I am thinking about cases where it is possible to use one product with several other products. In those cases the trade names are not always very similar which makes it not possible to deduce what products are to be used together.
Of course it is true that this information is not part of a printed SDS, but the information may be important for health protection and therefore we would like to have a way to communicate it.

**Comment by dirk-qualisys** [comment]
The necessary IDs would be provided by the other fields in ProductIdentity. As of today:

![partofset](https://cloud.githubusercontent.com/assets/4411785/11371851/cf3fcc8a-92ca-11e5-8304-34a01124a558.jpg)

So for any instance of product identity, you would have the additional boolean field. If false, the SDS describes the identified product. If true, the identified product is a kit or set which contains the product described in the SDS. I would expect (and enforce via any available means of validation) that at least one instance of ProductIdentity with PartOfSet = false exists, in order to describe the product itself.

As a side note, while I consider this info useful, it will not be available and/or maintained in many real-life cases...

**Comment by QuenzelGISBAU** [comment]
You are right a boolean field would solve this. I am not sure if I understand your sentence:

*If true, the identified product is a kit or set which contains the product described in the SDS* 

I don't want to refer to a product that contains the product described in the SDS. I want to refer to the other parts of the kit. But maybe that's what you are talking about and I just don't get it.

While I think you are right that a lot / most product databases might not maintain this info, I still think it would be great to have means of communicating it.

**Comment by dirk-qualisys** [comment]
OK, this was a major misunderstanding. The solution I outlined would refer to products that _contain_ the product described in the SDS. ProductIdentity is _not_ an appropriate place to refer to other parts of a set or kit.

To be honest, I don't think the requested info is part or should be part of the SDS, and SDScom currently focuses on the SDS. So I will bring this to the attention of the steering committee, as a scope question.

If this should be included, I propose to form a complex type for ProductIdentity and use this for an element ProductIdentity (as today) as well as for an additional element ToBeUsedWith.

**Comment by dirk-qualisys** [comment]
Postponed as not sufficiently discussed when 4.2.1 is released.

**Comment by dirk-qualisys** [comment]
Discussed today face to face. Kit SDSs are not feasible (or, if they are, they are in fact a group SDS). Thus there will be no structural support. Two annotations in Product Identity describe the situation.

**Comment by dirk-qualisys** [comment]
Proposed new phrase for kits to EuPhraC to support what is written in the annotations.
