### ISSUE TITLE
Erweiterung von EDASxChem: IsHazardousComponent

### ISSUE THREAD

**Issue by Henrich-BGRCI** [esdscom/sdscom-xml#34]
3.2.1.4.2.	**IsHazardousComponent**	xs:boolean	0:1  

Die Aufnahme des Feldes in EDASxChem ist beabsichtigt.  
(siehe https://github.com/esdscom/sdscom-xml/wiki/subsets-EDASxChem-and-EDASxBau)

Unterhalb des Knoten 3.2.1.4 ComponentInformation sind bereits die Felder 3.2.1.4.1. OnLabel, 3.2.1.4.3. IsOccupationalExposureLimit, 3.2.1.4.4.	IsBiologicalLimitValues,3.2.1.4.5. IsImpurity, 3.2.1.4.6.	IsStabilizer, 
3.2.1.4.8.	IsToxicologicalValues und 3.2.1.4.9.	IsEcoToxicologicalValues Teil von EDASxChem.

**Comment by dirk-qualisys** [comment]
Agree

**Comment by Henrich-BGRCI** [comment]
The field 3.2.1.4.2. IsHazardousComponent is added newly to EDASxChem 4.2.0.
