### ISSUE TITLE
Erweiterung von EDASxChem: StateUnderStandardConditions

### ISSUE THREAD

**Issue by Henrich-BGRCI** [esdscom/sdscom-xml#35]
In Section: 9.1.  Information on basic physical and chemical properties  
9.1.2.	**StateUnderStandardConditions**	Phrase	0:n

Die Aufnahme des Feldes in EDASxChem ist beabsichtigt.
 (siehe https://github.com/esdscom/sdscom-xml/wiki/subsets-EDASxChem-and-EDASxBau)

**Comment by dirk-qualisys** [comment]
Agree.

**Comment by Henrich-BGRCI** [comment]
The field 9.1.2. StateUnderStandardConditions is added newly to EDASxChem 4.2.0.
