### ISSUE TITLE
SDSComXMLNE_DE.xsd - New GISCODES

### ISSUE THREAD

**Issue by QuenzelGISBAU** [esdscom/sdscom-xml#37]
There are new GISCODES. Even though the product groups they represent are not officially adopted by the industry yet, the codes themself are already defined and should be included in the next SDScomXML update.
The new entries in SDSComXMLNE_DE.xsd should be:

<xs:enumeration value="BSW10"/>
<xs:enumeration value="BSW20"/>
<xs:enumeration value="BSW30"/>
<xs:enumeration value="BSW40"/>
<xs:enumeration value="BSW50"/>
<xs:enumeration value="BSW60"/>
<xs:enumeration value="BSL10"/>
<xs:enumeration value="BSL20"/>
<xs:enumeration value="BSL30"/>
<xs:enumeration value="BSL40"/>
<xs:enumeration value="BSL50"/>
<xs:enumeration value="BSL60"/>
<xs:enumeration value="HSW10"/>
<xs:enumeration value="HSW13"/>
<xs:enumeration value="HSW20"/>
<xs:enumeration value="HSW23"/>
<xs:enumeration value="HSW27"/>
<xs:enumeration value="HSW30"/>
<xs:enumeration value="HSW33"/>
<xs:enumeration value="HSW37"/>
<xs:enumeration value="HSW40"/>
<xs:enumeration value="HSW50"/>
<xs:enumeration value="HSL10"/>
<xs:enumeration value="HSL17"/>
<xs:enumeration value="HSL20"/>
<xs:enumeration value="HSL27"/>

**Comment by QuenzelGISBAU** [comment]
Somehow the list in the last post got cut. So here it is again in another format:

&lt;xs:enumeration value=&quot;BSW10&quot;/&gt;
&lt;xs:enumeration value=&quot;BSW20&quot;/&gt;
&lt;xs:enumeration value=&quot;BSW30&quot;/&gt;
&lt;xs:enumeration value=&quot;BSW40&quot;/&gt;
&lt;xs:enumeration value=&quot;BSW50&quot;/&gt;
&lt;xs:enumeration value=&quot;BSW60&quot;/&gt;
&lt;xs:enumeration value=&quot;BSL10&quot;/&gt;
&lt;xs:enumeration value=&quot;BSL20&quot;/&gt;
&lt;xs:enumeration value=&quot;BSL30&quot;/&gt;
&lt;xs:enumeration value=&quot;BSL40&quot;/&gt;
&lt;xs:enumeration value=&quot;BSL50&quot;/&gt;
&lt;xs:enumeration value=&quot;BSL60&quot;/&gt;
&lt;xs:enumeration value=&quot;HSW10&quot;/&gt;
&lt;xs:enumeration value=&quot;HSW13&quot;/&gt;
&lt;xs:enumeration value=&quot;HSW20&quot;/&gt;
&lt;xs:enumeration value=&quot;HSW23&quot;/&gt;
&lt;xs:enumeration value=&quot;HSW27&quot;/&gt;
&lt;xs:enumeration value=&quot;HSW30&quot;/&gt;
&lt;xs:enumeration value=&quot;HSW33&quot;/&gt;
&lt;xs:enumeration value=&quot;HSW37&quot;/&gt;
&lt;xs:enumeration value=&quot;HSW40&quot;/&gt;
&lt;xs:enumeration value=&quot;HSW50&quot;/&gt;
&lt;xs:enumeration value=&quot;HSL10&quot;/&gt;
&lt;xs:enumeration value=&quot;HSL17&quot;/&gt;
&lt;xs:enumeration value=&quot;HSL20&quot;/&gt;
&lt;xs:enumeration value=&quot;HSL27&quot;/&gt;

**Comment by QuenzelGISBAU** [comment]
I had another look at the list of GISCODES in the national extentions. There are still some codes missing, namely:
```XML
<xs:enumeration value="BTM 5"/>
<xs:enumeration value="BZM10"/>
<xs:enumeration value="BZM20"/>
<xs:enumeration value="BZM30"/>
<xs:enumeration value="BZM40"/>
<xs:enumeration value="BZM50"/>
<xs:enumeration value="GD13"/>
<xs:enumeration value="GD33"/>
<xs:enumeration value="GD45"/>
<xs:enumeration value="GD55"/>
<xs:enumeration value="GF10"/>
<xs:enumeration value="GF20"/>
<xs:enumeration value="GF30"/>
<xs:enumeration value="GF40"/>
<xs:enumeration value="GG43"/>
<xs:enumeration value="GG53"/>
<xs:enumeration value="GG63"/>
<xs:enumeration value="GGL05"/>
<xs:enumeration value="GS15"/>
<xs:enumeration value="GS18"/>
<xs:enumeration value="GS35"/>
<xs:enumeration value="GS38"/>
<xs:enumeration value="GS45"/>
<xs:enumeration value="GS48"/>
<xs:enumeration value="GS85"/>
<xs:enumeration value="GT20"/>
<xs:enumeration value="GU73"/>
<xs:enumeration value="GU83"/>
<xs:enumeration value="GU88"/>
<xs:enumeration value="GU93"/>
```

**Comment by dirk-qualisys** [comment]
Should go into the next version unless there are urgent requests for this.
