### ISSUE TITLE
Physical State under standard conditions

### ISSUE THREAD

**Issue by dirk-qualisys** [esdscom/sdscom-xml#4]
/DatasheetFeed/Datasheet/PhysicalChemicalProperties/Appearance/PhysicalState is of phrase type and not in any way restricted. Safety data sheets tend to describe the form of the product in delivery state in this place. It should be documented that this is not just solid/liquid/gaseous, but also pasty, Aerosol, powder, ...

SDSs tend to add a field for physical state (only solid/liquid/gaseous) under standard conditions (20°C, 1013 hpa). This should be added here as well.

**Comment by dirk-qualisys** [comment]
Has been added as DatasheetFeed/Datasheet/PhysicalChemicalProperties/Appearance/StateUnderStandardConditions in draft of June16, 2015.

**Comment by dirk-qualisys** [comment]
Was added as type string. Should be enum or phrase instead.
Excel documention mentions tag name UnderStandardConditions while XSD has StateUnderStandardConditions.

**Comment by nils-eska** [comment]
Has been changed in the XLS Documentation
