### ISSUE TITLE
BurningNumber

### ISSUE THREAD

**Issue by Henrich-BGRCI** [esdscom/sdscom-xml#42]
I just came across to the datatype BurningNumber but I could find, where it is used and can be placed in the xml, respectively.

**Comment by dirk-qualisys** [comment]
This describes flammability and burning behaviour of dust layers and is a possible property for section 9.2 - or oxidising properties in 9.1?

Nils, has this been dropped on error or purpose?

**Comment by nils-eska** [comment]
This Element has been discared in 2012 during the coordination with the Norwegian working Group. If it is needed we could reintroduce it. Otherwise this element should be deleted.
