### ISSUE TITLE
%, %volumne or %weight?

### ISSUE THREAD

**Issue by Henrich-BGRCI** [esdscom/sdscom-xml#45]
Which unit should be used in UnitIdEnum to destinguish between %volumne and %weight? At the moment, only %=9269144102 is given.

E.g. in PIB, %vol pib=10016, Volume pecent and %wt pib=10017, Weight percent are defined.

**Comment by dirk-qualisys** [comment]
9269144148 = Vol-%
9269144149 = weight-%

I will add both.
