### ISSUE TITLE
lines of comments in for ReasonForWaiving and PercentageValue

### ISSUE THREAD

**Issue by Henrich-BGRCI** [esdscom/sdscom-xml#47]
just code style: A separating comment line is missing in SDSComXMLDT for the new simpleType ReasonForWaiving and the complexType PercentageValue.

https://github.com/esdscom/sdscom-xml/commit/7c9ac5c711d4dcbdabcd3df7bc1f842807093414#diff-61e2812143d8bc328902504e483d2ffb

**Comment by dirk-qualisys** [comment]
Thank you - I was not paying attention to comments so far, because I work with a graphical XML tool. I fixed this nevertheless and will keep an eye on comments in future.
