### ISSUE TITLE
HazardStatement/FullText minOccurs

### ISSUE THREAD

**Issue by Henrich-BGRCI** [esdscom/sdscom-xml#48]
In the datatype HazardStatement, the element PhraseCode (HazardStatementEnum) has an occurance of exactly 1, but the FullText (string512) has an occurance of 0 to 1. This must be only 1 because the human-readable fulltext is required and sometimes cannot be derived from the PhraseCode.

**Comment by Henrich-BGRCI** [comment]
Same also for PrecautionaryStatement, SupplementalHazardInformation and SpecialSupplementalLabelInfo.

**Comment by nils-eska** [comment]
It should be possible to exchange phrases within a SDS only with a code. If the code is not sufficient for identification, the exporting system is responsible to add a full text, if needed with merge phrases.

**Comment by dirk-qualisys** [comment]
I agree with Nils. It's not a bug, it's a feature (and used in real life already).
