### ISSUE TITLE
best practice: atomisation of fields?

### ISSUE THREAD

**Issue by Henrich-BGRCI** [esdscom/sdscom-xml#49]
What is the best practice to fill fields of type Phrase? E.g., if the field 4.2.1 SymptomsAndEffectsGeneral contains several symptoms. Should they be split into several Phrase instances?

Furthermore, if there is e.g. the same description to each instance (e.g. EmergencyPhone/No and EmergencyPhone/EmergencyPhoneDescription), should/must the description be added to each instance?

**Comment by nils-eska** [comment]
The best way to exchange content is always to have the content split into independent capsuled phrases. In general this makes the translation much easier.
In the case of the EmergencyPhone it should be avoided to have redundant content.

**Comment by Henrich-BGRCI** [comment]
If e.g. the EmergencyPhoneDescription is not filled in each istance of EmergencyPhone (even if it is redundant), than it is unclear to which EmergencyPhone/No it belongs to. Therefore, I think, the following sentence should be transfered like this (here, EmergencyPhone is used just as an example to illustrate):
Emergency phone: available 24 h: +49 0123 45678 or +49 0123 11111 

            <EmergencyPhone>
                <No>+49 0123 45678</No>
                <EmergencyPhoneDescription PhraseCatalogueId="0">
                    <FullText>24 h</FullText>
                </EmergencyPhoneDescription>
            </EmergencyPhone>
            <EmergencyPhone>
                <No>+49 0123 11111</No>
                <EmergencyPhoneDescription PhraseCatalogueId="0">
                    <FullText>24 h</FullText>
                </EmergencyPhoneDescription>
            </EmergencyPhone>

**Comment by dirk-qualisys** [comment]
In the case of EmergencyPhone, I think the provided example makes perfect sense because each phone number could be available 24/7 or during office hours only. However, I don't like the redundancy (especially after importing!) which could be avoided if we add a field EmergencyPhoneComments which applies to all phone numbers, as found in other parts of the XSD.

We have to weigh if the straightforward structure in today's XSD or the better data representation takes preference. I have a slight tendency to use Mr Henrich's representation, which would translate into

          Phone: +49 0123 45678 (24 h)
          Phone: +49 0123 11111 (24 h)

after importing.

**Comment by Henrich-BGRCI** [comment]
The problem of redundancy is not restricted to EmergencyPhone but also affects many other bundled fields. In general, from the point of database structure redundancy is the standard situation in normalized databases. I think adding more fields to parent nodes does not solve the problem; therefore, redundancy cannot be avoided. 

Some more examples with the same problem: 8.5.3.11 HandProtectionEquipment, 11.1.1 TestResults, and all unbound fields with datatypes like PhysChemValue, PhysChemUnitValue, EcoToxicity, ...

**Comment by dirk-qualisys** [comment]
Adding parent nodes is IMHO the only way to avoid redundancy to achieve normalisation. But it should only be used for information that originally applies to the topic as a whole. Thus I think we should not apply this technique to nodes where the information is bound to a specific entry (emergency phone, PhysChem values of any kind, etc.). 

However, there might be additional, more general info which requires a matching field. For hand protection, the unbound fields are phrases, meaning that there can be a lengthy text of any structure to describe i.e. gloves. In addition, there is HandProtectionComments which would cover any general information.

**Comment by dirk-qualisys** [comment]
May I draw the conclusion that this has to be discussed on a case-by-case basis, as for hand protection in issue #56 ? In that case (and if nobody wants to add anything) I suggest to close this issue here.
