### ISSUE TITLE
Field Phone too short

### ISSUE THREAD

**Issue by dirk-qualisys** [esdscom/sdscom-xml#5]
is string40, should be longer

**Comment by dirk-qualisys** [comment]
Changed to string256

**Comment by dirk-qualisys** [comment]
XLS Documenation says string255 which does not exist!

**Comment by nils-eska** [comment]
Changes have been made in the XLS Documenation
Phone and EmergencyPhone/No string255 -> string256
Fax from string40 to string256

**Comment by QuenzelGISBAU** [comment]
Change documentation at the beginning of SDSComXML4.2.0.xsd also refers to  a maximum string length of 255.

**Comment by dirk-qualisys** [comment]
Thanks for the hint! Documentation was fixed for next release.
