### ISSUE TITLE
Current XmlStandardVersionEnum missing?

### ISSUE THREAD

**Issue by Suter-IK** [esdscom/sdscom-xml#52]
I would have expected to find XmlStandardVersionEnum=4.2.1. in the current release.

**Comment by nils-eska** [comment]
Fixed!

**Comment by dirk-qualisys** [comment]
See commit f3f3ea7 by Nils. Apologies for forgetting this in Release 4.2.1!

**Comment by dirk-qualisys** [comment]
I have just created a bugfix release https://github.com/esdscom/sdscom-xml/releases/tag/v4.2.1.1 . Please note that this should not require a new version number again, but all releases 4.2.1.x should be treated as version 4.2.1 and the newest available code should be used.
