### ISSUE TITLE
Disposal text for packing / product without having a waste code

### ISSUE THREAD

**Issue by Suter-IK** [esdscom/sdscom-xml#53]
I have text for disposal of packing and other text for disposal of product but I don't have any waste codes. Therefore it's not possible to use "EWLPacking-WasteDescription" or "EWLProduct-WasteDescription" for those texts, because "WasteCode" is mandatory. 

1/ I used "WasteTreatmentMethods" instead to transfer the information into XML: both packing and product texts are in one field and cannot be distincted.
2/ I again used "WasteTreatmentMethods" but added subtitles ("Ungebrauchtes Produkt" / "Ungereinigte Verpackungen") as additional phrases into XML. See file: [Question-Waste.txt](https://github.com/esdscom/sdscom-xml/files/79840/Question-Waste.txt) 

What's could be a better approach to solve this problem?

**Comment by dirk-qualisys** [comment]
Your way is fine for the export part, but difficult for importing because it looses a valuable structure info (product vs. packaging). Thus I suggest we make the WasteCode optional so that WasteDescription can be used without codes. What do you think?

**Comment by Suter-IK** [comment]
WasteDescription allows only one phrase which is not enough for me. 
Furthermore I expect under WasteDescription something like "Red liquid, fuming". 
I have two suggestions: [WasteTreatmentMethods.xlsx](https://github.com/esdscom/sdscom-xml/files/81369/WasteTreatmentMethods.xlsx)
My favorite is number 1.

**Comment by dirk-qualisys** [comment]
Waste treatment methods are not part of the European Waste List, so I think your number 1 is better than number 2 and better than my original suggestion to use WasteDescription (even if modified to be unbounded). I would like to learn why you want a field "General": What would you want to describe, other than "Product" and "Packaging"?

**Comment by dirk-qualisys** [comment]
What would you think of this structure which is backwards compatible (and thus allows us to change this in v4.2.2):

![waste](https://cloud.githubusercontent.com/assets/4411785/12395558/a8180c22-be02-11e5-8603-b470edbd2853.jpg)

**Comment by dirk-qualisys** [comment]
As there were no comments, I will commit the above change so that everybody can test it.
