### ISSUE TITLE
Restriction of float8 values

### ISSUE THREAD

**Issue by Alexander-sipro** [esdscom/sdscom-xml#54]
I get trouble with the precision of the float8 values widely used in the SDScom specification. When writing a UnitValue in scientifical representation like -1.25E+04, it is not possible to use more than one decimal after the comma. It would be nice to have for example 4 digits after the comma to make sure not loosing precision.

I have seen there is also a float11 or even float16 definded, but not used in the whole xsd specification. So would it maybe possible to use these instead of float8 in the next version?

**Comment by dlichtenberger-chemdox** [comment]
I agree that float8 seems overly restrictive. In your case you could save two characters, though (-1.25E4).

**Comment by dirk-qualisys** [comment]
No problem to change that in general.

I believe it is meant to be restrictive to avoid data that makes no sense. As you all know, float 8 has a precision of 8 digits, i.e. it would have 7 digits after the comma if there is just one before the comma. So I suggest to analyse if there are cases where we have cases like -1.25E4 = -12500 which need a precision of more than three digits after the comma. 

float8 is used in Value, UnitValue and all related types. What are real-life cases where you would need a higher precision? If in doubt, I would vote for changing it, but currently  I can't see any phys/chem property that would allow measurement with a higher precision.

**Comment by nils-eska** [comment]
I agree with Dirk.
It is no problem to change the float8 restriction to a more detailed one. The backward compatibility is given, but we should only change it if it is necessary.

**Comment by Alexander-sipro** [comment]
The thing is that so far we use only the scientifical representation, so values like for example a melting point of -114,5 °C or a boiling point of 78,32 °C cannot be exactly represented. So this seems a bit too restrictive to me, especially as a higher possible precision does not mean that you have to use it, but you can in cases you need it.

**Comment by dirk-qualisys** [comment]
Good point. So what is the use of having three different float values? Why not have a float value without length limitation, i.e. use the standard xs:float type? In that, just the constraints of source and target system would limit the precision, but not the XML.

I would rather prefer having a float type that checks for value ranges (e.g. 0 to 100, for percent values) but have not yet found a way to implement this in XSD.

**Comment by nils-eska** [comment]
I think, there is no reason for using the different float values. We should use the standard xs:float type and drop all other.

**Comment by Alexander-sipro** [comment]
I perfectly agree with both of you that a standard float type would do it in this case and is the most flexible solution. Then we can keep our solution of just using the scientifical notation in the XML and make it as long as it needs to be. 
So this will be changed in version 4.2.2. ?

**Comment by dirk-qualisys** [comment]
Yes, milestone is 4.2.2, and the change is available now for testing.

A very precise and comprehensive, but German description of the technical background is available at http://www.data2type.de/xml-xslt-xslfo/xml-schema/datentypen-referenz/xs-float/
