### ISSUE TITLE
DoseEnum: ATEmix tested?

### ISSUE THREAD

**Issue by dirk-qualisys** [esdscom/sdscom-xml#57]
DoseEnum offers two different values für ATE: "ATEmix tested" and "ATEmix calculated". To my understanding, an ATEmix is always calculation (from LC/LD50 and ATE values of the ingredients). As soon as I have a test result, this should be communicated as LC/LD50.

Can anybody shed some light how "ATEmix tested" should be used? Or is this an error?

**Comment by nils-eska** [comment]
The "ATEmix tested" is not relevant for an EU safety datasheet and we should drop this value.
As far as I know, "ATEmix tested" is used in other regions outside of the EU and was proposed by the Norwegian project.

**Comment by dirk-qualisys** [comment]
EuPhraC discussed this briefly and came to the concluson that ATE's are always calculated. So both values should be dropped and "ATEmix" intrioduced until there is some official proof that this is needed.

Thus relabeled as refactoring (although it would qualify as a bug, but of minor importance) and assigned to 4.3
