### ISSUE TITLE
unitId: ambiguous mappings for g/l and g/m3

### ISSUE THREAD

**Issue by dlichtenberger-chemdox** [esdscom/sdscom-xml#60]
The EuPhraC unit mappings in the UnitIdEnum comments have two ambiguous entries:

"g/m3": [9269144164, 9269144145]
"g/l": [9269144140, 9294211175]

In EuPhraC 1.3, I found the following:
9269144164 = g/m3
9269144145 = g/m
9269144140 = g/L

I did not find 9294211175.

**Comment by dirk-qualisys** [comment]
Completely true, plus one entry appeared twice in the enumerations.
