### ISSUE TITLE
General definition of version numbers / workflow for structural changes

### ISSUE THREAD

**Issue by dirk-qualisys** [esdscom/sdscom-xml#61]
I would like to raise an issue that has been discussed between EuPhraC and some SDScom members recently. 

We need to establish a formal process to check structural consistency between both projects (in order to improve quality and maintainability). Since software companies do not like to change their implementations too often, we should clearly differentiate between versions that change structure (i.e., are incompatible with previous versions to a certain degree), and others which only apply minor changes that do not affect the general structure.

Thus we would like to propose the following refinement of the current version numbering definition:

1. digit (unchanged): defines the scope. Currently 4 = document-based approach for European SDS. 5 aims at a product-based approach. Certainly requires change in software implementation.
2. digit (new): structural change or other incompatibilites. If this number changes, the structure may change, deprecated fields or values may be deleted, etc. Will often require software implementation changes.
3. digit (unchanged): incremental, but backwards compatible changes. Will in most environments not affect existing software at least for the export side, but may add fields which would be ignored when importing in older implementations.
4. digit (unchanged): maintenance releases, usually for bug fixes.

Changes of the second digit / structure should not occur more than once a year, i.e. more than in every second release. We still have to talk with ESCom and SDBtransfer about this proposal, but if there are no objections, this would likely mean that we create version 4.3.0 either in April or in October 2016.

Please share your thoughts.

**Comment by Henrich-BGRCI** [comment]
I think the proposal for the version number is fine and better than the old one, because it looses the unnecessary reference to the version number of EuPhraC (e.g. 2.1). 
See also issue SDScom versioning when no changes occured#39.

**Comment by dirk-qualisys** [comment]
I am afraid this is a misunderstanding and apologize for not being clear enough. We will continue with sync'ed releases for SDScom and EuPhrac, and because the structure of both needs to match, agreement between the projects is necessary to decide when structural changes will take place. Thus the matching version numbers are indeed necessary and will stay.

The proposal introduces a new definition/meaning for the third number and gives us the flexibility to introduce structural (i.e. incompatible) changes earlier than v5 which is meant to shift the paradigm and/or scope. This allows for more time to discuss the new paradigm, without delaying improvements in v4.

**Comment by QuenzelGISBAU** [comment]
I'm not really a friend of structural changes without a new paradigm. I understand that this somewhat frustrating, because the existing version is not perfect but I think it's more important to guarantee stable long living versions.
Also in last year October we agreed on maintaining version 4 for a longer period of time and this approach kind of contradicts the point of that, doesn't it?
I think on the other hand that a release of version 5 as fast possible (maybe October 2016?) would be great, so there is a version where those improvements will have been made.

**Comment by dirk-qualisys** [comment]
We cannot guarantee a paradigm shift whenever structural changes are necessary. Plus, during the SDBtransfer final workshop in Berlin last week, some people expressed the opinion that we should be careful introducing a paradigm shift before more implementations are available.

So a possible approach would be to use the described versioning approach (v 4.2.2 in spring and v4.3.0 including structural changes in autumn) and discuss the scope of version 5 in the October workshop. What do you think?

**Comment by QuenzelGISBAU** [comment]
That sounds reasonable to me.

> ...some people expressed the opinion that we should be careful introducing a paradigm shift before more implementations are available.

I feel exactly the same about to many structural changes, since both trigger a significant amount of work (obviously a paradigm shift more so).
To conclude: I don't mind the change 4.2.1 to 4.3.0 (especially in October) but think structural changes in general should be done as seldom as possible. Particularly before more people implement the format.

**Comment by dirk-qualisys** [comment]
OK, as there are no further comments, I will treat this as agreed. We can discuss in the release meeting for v2.2 in April if the next version should include structural cleanups (v4.3.0) or not (v4.2.3).
