### ISSUE TITLE
Length of VersionNo

### ISSUE THREAD

**Issue by Suter-IK** [esdscom/sdscom-xml#62]
Currently SDSCom uses string10 for VersionNo. Our system allows up to string64. I propose to change VersionNo to string64.

**Comment by dirk-qualisys** [comment]
Generally, this is no big deal, but with the change we force all systems to work with this length. As I am only used to version numbers like "10.3" for safety data sheets, can you please provide a real-life example which is longer than 10 characters (for documentation purposes)?

**Comment by Suter-IK** [comment]
I checked all versions in our system and found things like "CLP 1.0.2 / Suter". From my point of view, there is no need for an sdscom adaptation, we will force our customers to use more reasonable version descriptors.

**Comment by dirk-qualisys** [comment]
Thank you, this is an interesting info. Would it make sense to clarify our expectation for SDS version numbers by applying a pattern like:

\d+(?:\.\d+){0,3}
\d+(?:\.\d+[a-z]*){0,3}
\d+[a-z]*(?:\.\d+[a-z]*){0,3}

Or should we simply leave the element as today?

**Comment by Suter-IK** [comment]
I do not need a regex pattern here and would prefer to leave it as it is.
