### ISSUE TITLE
TestReference vs. Method

### ISSUE THREAD

**Issue by Henrich-BGRCI** [esdscom/sdscom-xml#65]
What is the definition for TestReference in contrast to Method (e.g. in PhysChemUnitValue)?

For example: MeltingPoint: 40 °C at 1013 hPa
The parameter pressure (1013 hPa), should it be placed in TestReference, Method or just in Comments?

**Comment by dirk-qualisys** [comment]
TestReference is connected to the method, like the test parameter "blood" for biological limit values probably. But I am also lacking a good example for the cases in which PhysChemUnitValue is used.

Air pressure is an influencing factor like temperature, so I would currently put it in comments (if necessary, i.e. other than the standard air pressure only). Should we introduce air pressure next to temperature as a separate UnitValue??

**Comment by Henrich-BGRCI** [comment]
Before we introduce a further field UnitValue for pressure, we should check whether there are other parameters used for physical properties.

**Comment by dirk-qualisys** [comment]
Certainly true. My idea was derived from the definition of "normal conditions" as 20 °C, 1013 hPa (but I can't remember the source of this definition). Thus I expect these two parameters to be relevant for test results in case any tests took place under different circumstances.

Anybody aware of additional parameters or the source of the above mentioned definition?

**Comment by nils-eska** [comment]
Has far is I know, with only a few exceptions, temperature and/or pressure are needed information for conditions for physical or chemical values, and only if these differ from the standard conditions or the conditions given by the test method.
Only if it is really needed to provide conditions not covered by the method or the standard definition, we should introduce an extra value for the condition.

**Comment by Suter-IK** [comment]
A customer of us needs additional parameters for dynamic viscosity. The string looks like this: 
200-400 mPa*s  Condition: Spindel L1 / 20 U/min / 20°C  Norm: ISO 2555
For reference, look here: http://www.trilogica.de/blog/rotationsviskosimeter/
But from my point of view and to keep sdscom lean, this has not to be added. I write the condition part into comments as I do it now with a pressure value.

**Comment by dirk-qualisys** [comment]
Usually, the methods that are accepted under CLP / GHS are clearly defined. To my understanding (I have no access to the full EN ISO 2555) the Brookfield test described there results in a value, and the equipment is chosen depending on the circumstances, i.e. the test substance and expected value range. So for the purpose of the SDS, value and method would be sufficient, while for a scientific paper like a registration dossier you would need to describe the test apparatus und the study reliability further.

So it seems sensible to use value and method, and provide other information in comments if the user feels this is helpful. If the above is correct, this brings us back to the question if pressure needs to be added to values if temperature can be specified. Please comment.

**Comment by Suter-IK** [comment]
Shall pressure be added to values as we have it with temperature?
I went through 1893 boiling points (real data entries from our customers) and found 101 having a pressure reference. This was more than I expected and therefore I can answer the above question with "Yes".

**Comment by dirk-qualisys** [comment]
Discussed today face to face. Pressure will be added.
