### ISSUE TITLE
SupplierInformation minOccurs

### ISSUE THREAD

**Issue by Henrich-BGRCI** [esdscom/sdscom-xml#67]
Currently, the SupplierInformation has no minOccurs, but according to REACH this should be minOccurs="1", which is also given in the SDScom-excel-table.

**Comment by dirk-qualisys** [comment]
Should be a no-brainer since every SDS has to have supplier information. Thus I vote to treat this as a bug and fix it in 4.2.2 already although technically incompatible if changed.

**Comment by dirk-qualisys** [comment]
Just starting to fix this, I saw that the XSD already has miOccurs=1, so there is nothing to fix. Sorry for not looking this up earlier.

**Comment by Henrich-BGRCI** [comment]
The current master version of SDSComXML.xsd has in line 318:
	<xs:element name="SupplierInformation" maxOccurs="unbounded">

**Comment by Henrich-BGRCI** [comment]
xs:element name="SupplierInformation" maxOccurs="unbounded"

**Comment by dirk-qualisys** [comment]
Correct. The default for minOccurs is 1 (non-optional element) as you may check with graphical XML tools. Please compare with

\<xs:element name="Role" minOccurs="0" maxOccurs="1"\>
