### ISSUE TITLE
WasteCode in different notation

### ISSUE THREAD

**Issue by Suter-IK** [esdscom/sdscom-xml#68]
I found a different notation for waste codes, e.g.  060902  (without spaces) and also a few of our customers use this notation from time to time. See also this reference: 
http://www.statistikportal.de/Statistik-Portal/Abfallkatalog.pdf
What do you think of updating the WasteCode Regex from 
[0-9]{2} [0-9]{2} [0-9]{2}  to ([0-9]{2} [0-9]{2} [0-9]{2})|([0-9]{6})

**Comment by dirk-qualisys** [comment]
This is something you could dispute for the storage classes in Germany as well: should the very same value be stored as LGK 8A, LGK 8 A, 8A or 8 A? I believe it is worth to agree on just one format, remembering that this is just for data echange. 

Any application is free to reformat the content according to customer preferences. This already applies to decimal separators in numbers, date/time formats and so on.
