### ISSUE TITLE
Drop Excel schema description (e.g. IsToxicologicalValues vs IncludeToxicologicalValues)

### ISSUE THREAD

**Issue by dlichtenberger-chemdox** [esdscom/sdscom-xml#69]
In the SDSCom/EDAS Excel overview file (SDSComXmlStandard_EDASxChem-Bau-4.2.0.xls), the following elements are misnamed:

IsPhysicalValues
IsToxicologicalValues
IsEcoToxicologicalValues

should be:

IncludePhysicalValues
IncludeToxicologicalValues
IncludeEcoToxicologicalValues

This also applies to the EDASxCHEM stylesheet.

**Comment by Henrich-BGRCI** [comment]
Thank you for the hint. This not a EDASx-only issue, because for the subset definition the excel table of SDScomXML version 4.2.0 was used. Here, an update of the table to the current version is needed first before using for subset definition.

**Comment by dirk-qualisys** [comment]
The reason for labeling was that the Excel file is no longer maintained for SDScom after moving to GitHub, if I remember correctly, but only to keep track of substandard definition. Thus I thought/think that this is part of the substandard (project) tasks.

Question is if and how the substandard definition is updated in future. I am afraid we should have discussed this in Berlin. Do we need the substandard definition in future or are EDASxBau/Chem dropped after this month? 

- If necessary, we will need to maintain the list of fields per substandard also in future.
- If we agree that everybody will move towards full SDScom implementation, we may want to follow up on the idea of defining an implementation score similar to http://html5test.com/

- Do we need he substardaIs is enough to archive the current status of definition, even if future versions may hange the definition of data fields?
-

**Comment by Suter-IK** [comment]
We are almost at the point, where we have a full sdscom export available. I kept EDASXChem in the header of my xml only to cover the needs of BGRCI. 
On the other hand, we should think at all of those, who didn't yet implement any XML export. It might be easier for a new Software vendor to start with a reduced set of fields.

**Comment by Henrich-BGRCI** [comment]
If the excel table is not longer maintained, the description given in the table should be transferred completly to the xsd. E.g., for the fields mentioned above I cannot find in the xsd any information about the default values as it given in the table.

**Comment by Henrich-BGRCI** [comment]
Here is an update of the EDASxChem (uncomplete SDScomXML) stylesheet: 
[EDASxChem_style_v4.txt](https://github.com/esdscom/sdscom-xml/files/136258/EDASxChem_style_v4.txt)
(just rename .txt in .xslt)

**Comment by QuenzelGISBAU** [comment]
I absolutely think the EDASxBau/Chem formats should not be dropped especially not this fast.
Therefore I agree with Mr. Suter. I Think at least for the next few years it is even essential to have EDASxBau/Chem just to have a well definiend entry point into the whole complex of themes.

Regarding the whole Excel Business. Those have to be maintained. But I think this is something the SDBtransfer project partners have to talk about and should not be discussed here.

**Comment by dirk-qualisys** [comment]
**To summarize:**

- The Excel files are not part of the current SDScom deliveries.
- Not all information in the Excel sheet is part of XSD or other documentation (yet), but the info is considered valuable
- The substandard definitions are helpful in future.

We can collect further input here and should discuss this in the Berlin workshop if no solution is agreed here before.

**Comment by dirk-qualisys** [comment]
Consensus is to transfer the information from the Excel file into the schema defition and mark the field for SDScomBau and SDScomChem, e.g. in annotations like this:

`		<xs:annotation>
			<xs:appinfo>SDScomBau</xs:appinfo>
			<xs:appinfo>SDScomChem</xs:appinfo>
			<xs:documentation>Explanation of the field...</xs:documentation>
		</xs:annotation>`

**Comment by Suter-IK** [comment]
What is the intention to keep the substandard definitions in future?

**Comment by dirk-qualisys** [comment]
These may help new implementors to understand which fields deliver the best use, or could be applied in certain applications (GISBAU), if SDScom is implemented partially. And I am not aware of any full implementation.

From an administrative side and for the sake of Germany's SDBtrasfer project, results should be preserved for a couple of years. Once transferred, the new annotations do not need maintenance (while the Excel files would). So I agree this is probably the best way to proceed, at least if the substandards should be maintained.

**Comment by Henrich-BGRCI** [comment]
According to the schema given above, I will transfer from the Excel table into the XSD the documentation, which is given in the table but missing in the xsd, as well as the subset Definition for Bau and Chem. Afterwards, the local copy of the xsd can be merged with the current version.
