### ISSUE TITLE
double unitId in UnitIdEnum

### ISSUE THREAD

**Issue by Suter-IK** [esdscom/sdscom-xml#72]
1/
Why do these ids occur twice in UnitIdEnum?
[doubleUnitEnumIds.txt](https://github.com/esdscom/sdscom-xml/files/140445/doubleUnitEnumIds.txt)

2/
How will this be solved in future when the EuPhraC id will be replaced by the unit's clear text? 
**g/l.s**    vs.    **g/l*s**   (Id of both= 9269144311) 
Do we have two different units after the intended change?

**Comment by Henrich-BGRCI** [comment]
Sorry, that was my fault. I overlooked the already given UnitId for %volumne and %weight; and they were added newly. See #45

**Comment by dirk-qualisys** [comment]
1/
Thank you both for the hints. I found 9269144257 and 9269144311 to appear twice as well. A commit will update the list today.

**Comment by dirk-qualisys** [comment]
2/
This is a representation question similar to issue #68. Each (semantical) value should be represented just once. For data exchange, it does not matter if the multiplying operator is represented as a dot or asterisk, and every software may recode this as necessary.
