### ISSUE TITLE
How can we best include "Restricted to professional users" in the XML file?

### ISSUE THREAD

**Issue by werner-axalta** [esdscom/sdscom-xml#74]
We are looking for the best place to include "Restricted to professional users" in the XML file because we have included this phrase in chapters 1 and 2 of our SDSs to inform customers / users that theses products are not for consumer use.

**Comment by Suter-IK** [comment]
I evaluate the phrase to a boolean and fill it into "CanBeUsedByTheGeneralPublic". The phrase does not appear in my XML.

**Comment by dirk-qualisys** [comment]
We have a similar approach: For data entry, we use a checkbox that evaluates directly to the boolean value. For output, we choose a phrase accordingly.

Are these two answers sufficient for you so that we can close this issue or is there anything else which needs consideration?

**Comment by werner-axalta** [comment]
Thanks for the answersthey were helpful. The issue can be closed.
