### ISSUE TITLE
Aquatic Toxicity

### ISSUE THREAD

**Issue by werner-axalta** [esdscom/sdscom-xml#75]
In our SDSs we are using as one species to test aquatic toxicity "Aquatic Invertebrates".
But we couldn't find this species in the list of values offered in the specification.
Is there any other option or synonym or do we have to add this as a custom tag?

**Comment by dirk-qualisys** [comment]
I have forwarded this to EuPhraC's expert for ecotoxicity for consideration, as EuPhraC needs to add this phrase as well (if the reply is positive).

**Comment by dirk-qualisys** [comment]
Reply from EuPhraC's expert: 

_"Aquatic invertebrates" is more a cetegory than a species, although a commonly used one. On other trophic levels, we use "fish" or "algae". Also there, it makes sense to name the respective species (e.g. zebrafish). Accordingly, "Aquatic invertebrates" should only be used as a last resort._

Thus OtherEcotoxInfoCrustaceans is the best place for such less specific information. I will add an annotation.
