### ISSUE TITLE
Exact content for ProperShippingName

### ISSUE THREAD

**Issue by dirk-qualisys** [esdscom/sdscom-xml#76]
What exactly is the content that should be sent in ProperShippingName\* ? If transportation would take place as "UN 2735, POLYAMINES, LIQUID, CORROSIVE, N.O.S. (Polyethylene amine)", what should be specified as the PSN:
- POLYAMINES, LIQUID, CORROSIVE, N.O.S. _[because UN number and danger releasing substance are specified separately]_
- UN 2735, POLYAMINES, LIQUID, CORROSIVE, N.O.S.
- POLYAMINES, LIQUID, CORROSIVE, N.O.S. (Polyethylene amine)
- UN 2735, POLYAMINES, LIQUID, CORROSIVE, N.O.S. (Polyethylene amine) _[because this is the real PSN]_

This is not even the most complex example: There is the prefix "waste" as well as postfixes "stabilized", "molten", "mixture", "solution", "probe" and "marine pollutant" that can become part of the proper shipping name as well. With the exception of "marine pollutant", they are not covered elsewhere, so I believe they must be covered in this field.

Are there any rules which of the above parts should form the ProperShippingName\* fields? If not, please use this issue to define/discuss a rule that should be added to SDScom finally.

**Comment by Suter-IK** [comment]
We discussed this question and found the following contribution to this based on ADR:
http://www.unece.org/fileadmin/DAM/trans/danger/publi/adr/adr2015/ADR2015e_WEB.pdf
http://www.astra.admin.ch/themen/schwerverkehr/00246/00406/06810/index.html?lang=de

1/ Shall the UN number be part of the proper shipping Name?
ADR 3.1.2.1: "The proper shipping Name (=offizielle Benennung für die Beförderung) is that portion of the entry...in Table A... shown in upper case". Numbers cannot be in upper case.
See also examples ADR 3.1.2.2. which shows UN number: "The proper shipping name is the most appropriate of the following combinations:
FERROUS METAL BORINGS 
FERROUS METAL SHAVINGS"
This example also leads to the interpretation that the UN number is not part of the proper shipping name. Nevertheless the UN number has to be on the shipping goods.

2/ Shall text after N.O.S. be stored in ProperShippingName* field?
The text after N.O.S. is called "technical name of the goods" (technischen Benennung des Gutes) and contains chemical name(s) with optional modifiers ("and", "contains", "containing", etc.) ADR 3.1.2.8.1  
An import software cannot decide by itself, where the modifiers should be written, between the chemicals or at the end? Therefore we suggest to fill the ProperShippingName* like this: 
POLYAMINES, LIQUID, CORROSIVE, N.O.S. (Isophorone diamine and Diethylene triamine)

**Comment by dirk-qualisys** [comment]
This sounds very reasonable to me (assuming that the ProperShippingName would as well include the prefix or postfixes that I cited before). Re-reading the transport carrier regulations, it seems that the parts of section 3.2 which show the UN number together with the PSN do this for reference only. 

Nils, can you confirm this (i.e., include everything but the UN number)?

**Comment by nils-eska** [comment]
The ProperShippingName is just the entry of Table A (ADR) shown in upper case. There is a separated Field for the danger releasing substance (the substance name in the brackets). Also for the information "marine pollutant" (IMDG) or "Environmental Hazard" (ADR) separate fields exist.

The prefix "Waste" and the postfixes "stabilized", "molten", "mixture", "solution", "probe" are not part of the ProperShippingName (and the SDS) because we do not know the usage of the product and the related dangerous goods declarations. That have to be defined by the dangerous goods safety advisor.

**Comment by dirk-qualisys** [comment]
We need to differentiate if we talk about PSN in the context of transport regulations or SDS. Annex II (regulation 2015/830) and the guidance are not very specific as they simply refer to UN model regulations, which in turn specify the PSN in table 3.1, but then also call it PSN after this is enhanced with the elements above. The SDS author can indeed judge on "mixture" or "solution" in most cases as the PSN describes the product in delivery state.

**Comment by dirk-qualisys** [comment]
Had a similar question, but in the context of a safety data sheet document recently. Unfortunately the term "Proper Shipping Name" is used for the entries in table 3.1 as well as their extended form with additions from Parts 3 and 5. In absence of clear guidance, the result of the discussion was:

- All informationen required by Part 3 of transport regulations can be decided by the SDS author and considered part of the Proper Shipping Name for SDS purposes. This includes (but is not restricted to) "mixture" and "solution" (IMDG 3.1.3), "molten", "stabilized", "temperature controlled" (all IMDG 3.1.2). While "marine pollutant" is referenced in an example in IMDG section 3.1.2.9.2, its application is not described in part 3.
- All information required by Part 5 of transport regulations (e.g. IMDG 5.4.1.4.3) is part of the shipping papers only. This includes "marine pollutant", which would be known by the SDS author, but also "empty, uncleaned", "residue last contained", "waste" etc. (where applicable) which usually cannot be decided by the SDS author or would not require a SDS anyway.

The UN number is not part of the proper shipping name according to Part 3 and should not be repeated here.
