### ISSUE TITLE
How to handle freely combined Precautionary statements?

### ISSUE THREAD

**Issue by dirk-qualisys** [esdscom/sdscom-xml#77]
It is allowed to combine P phrases where helpful. E.g., EuPhraC has a P phrase "P309+P310" that makes perfect sense, but is not part of CLP. SDScom however does not cover this in PrecautionaryStatementEnum so that this will not validate.

I believe it is no option to force importing/exporting systems to split those P phrases, because the resulting XML file would not reflect the SDS anymore. On the other hand, how can we enforce a restriction to meaningful phrases here? My best bet is to make the phrase code mandatory, but this would still allow _any _phrase code. Any optinions / better ideas?

**Comment by Suter-IK** [comment]
We restrict the combination of P phrases to the CLP set, we don't allow other combinations.
1/ Are there systems which allow free combinations and how do they manage the translation?
2/ Would it be an option to collect such combinations and forward them to Echa Helpdesk and wait for a new CLP release?

**Comment by dirk-qualisys** [comment]
Re 1/ Our system does. We basically handle those combinations as custom phrases which can carry codes as well, i.e. they are "normal" but non-standard phrases.
Re 2/ As CLP connects to UN-GHS and revisions are slow, I don't think this is quick enough if we request changes. But we might agree that we add all accepted combinations to EuPhraC and then also to SDScom. This would resolve the issue of alignment, for a start.

I labelled this as a bug because it is possible to create llegal SDSs which cannot be represented in SDScom. These are the options that can see:

- Just align EuPhraC and SDScom, and make sure additions take place quick enough. Limit to those "accepted" phrases. BUT: Still, other legal combinations would not be covered.
- Make PhraseCode optional. BUT: That lowers constraints considerably ad allows any wrong content.

**Comment by dirk-qualisys** [comment]
New idea: We could introduce a "phrase category" in EuPhraC that would then translate into a new attribute in SDScom's phrase data type. Instead of a list of specified P phrases, we would then restrict this to phrase category = "Precautionary Statement". The same works for H phrases, EUH phrases etc.

**Advantages:** This allows maintenance of the P phrase list in just one place (the phrase catalogue), thus ensuring consistency between EuPhraC and SDScom while the concept is still open for other phrase catalogues. It also allows user defined combined P phrases which must simply carry the right category.

**Disadvantage: ** It is possible to cheat the system by setting the right category on any phrase.

Opinions?

**Comment by QuenzelGISBAU** [comment]
I'm not quite sure if i get your idea. Could you maybe prepare an example?
Anyway, I don't like the idea of only allowing an "arbitrarily" subset of combinations like EuPhraC P phrase combinations. Everybody who is using a different phrase catalogue might run into problems this way.
I think a restriction based on a pattern would be better. Maybe something like `[0-9]{3}(\+[0-9]{3}){0,2}`?, but I'm not really comfortable with regular expressions.
Of course a disadvantage of this is that is possible to transfer not existig phrase codes.

**Comment by dirk-qualisys** [comment]
Jasper, I think this is brilliant! Herewith I would like to revoke my idea of a "phrase category" and support the concept of regular expressions for P phrases. 

**Advantages:** This allows to use any phrase catalogue and any P phrase combination. 
**Disadvantages:** It would certainly still allow useless combinations of P phrases and any other content with a proper code, but the latter requires almost criminal energy and thus I think that is the best solution discussed so far.

**Comment by Henrich-BGRCI** [comment]
Indepentently of the solution for the final datatype, I think, the possibility of freely combined precautionary statements shows nicely, that the FullText should be mandatory (minOccurs=0), see also #48. Moreover, even if a precautionary statement is given in PrecautionaryStatementEnum or in the current EuPhrC, older SDS may refere to different wording based on changes by ATP. To have the same information in the XML as in the printed SDS, this would require that the CLP version must be also given in the XML and that the importing systems have to track and know all former wordings of all precautionary statements.

**Comment by Suter-IK** [comment]
Remark to the above example (P309+P310):  P309 disappeared in ATP 4.
See: http://eur-lex.europa.eu/legal-content/DE/TXT/PDF/?uri=CELEX:32013R0487&rid=1   / Page 31

**Comment by dirk-qualisys** [comment]
True - P309 shoul dnot be used in new data. I took this example from an existing SDS for the sake of real-life relevance, but similar cases may occur anytime with other precautionary statements.

Regarding mandatory full texts, this has been discussed in full depth and decided in issue #48: "It should be possible to exchange phrases within a SDS only with a code. If the code is not sufficient for identification, the exporting system is responsible to add a full text, if needed with merge phrases."

Getting back to the original issue: Do you all agree with Jasper's solution to introduce regex for P phrase code checking? If the is no objection, I  will close this issue in a couple of days.

**Comment by QuenzelGISBAU** [comment]
Regarding the pattern: I just saw a SDS in which a combination of more than just 3 individual precautionary statements was used. I think it's a valid combination (305+351+338+310). Therefore I think the proposed pattern has to be altered to allow at least four individual statements.

**Comment by dirk-qualisys** [comment]
For easier reading, I suggest the pattern 

> \d\d\d(\+\d\d\d){0,3}

**Comment by dirk-qualisys** [comment]
Actually, I implemented a union of a list of legal p phrase codes and a sequence of two to four three-digit numbers. This gives us strict constraint for singular P phrases, but the necessary flexility for combinations. The only downside is that we cannot restrict the combinations to certain numbers.

**Comment by nils-eska** [comment]
From today's workshop in Hamburg: The type "PrecautionaryStatement" of Field "ClpPrecautionaryStatement" will be changed. 
- FullText will be set to manantory
- PhraseCode minOcc is 1
- PhraseCode maxOcc is 5
