### ISSUE TITLE
Transport Labels Chapter 14 SDS

### ISSUE THREAD

**Issue by werner-axalta** [esdscom/sdscom-xml#78]
We display the labels applicable for the transportation of dangerous goods in chapter 14 of the SDS.
But we haven't seen the option in the SDSCOM-XML specification to select the appropriate labels / label-codes and to insert this information in the XML document.
We learned that this is not a mandatory field but we believe that this would be a valuable enhancement as many suppliers show transport labels here.

**Comment by nils-eska** [comment]
The Label is part of "OtherTransportInformation" - "TransportHazardLabels", or do you mean something different?

**Comment by dirk-qualisys** [comment]
As there was no reply, I am guessing we can close this.
