### ISSUE TITLE
Kemler-Code in Chapter 14 SDS (Transportation)

### ISSUE THREAD

**Issue by werner-axalta** [esdscom/sdscom-xml#79]
We still use the Kemler-Code in our SDS in Chapter 14 to state the "Hazard Identification Number".
What is the best way to include this information so the XML document matches the corresponding pdf?

**Comment by nils-eska** [comment]
The correct Field for the Kemler-Code is "AdrHazardIdentificationNo" ("OtherTransportInformation" - "AdrOtherInformation"
