### ISSUE TITLE
Phrase with forced line break

### ISSUE THREAD

**Issue by thegbom** [esdscom/sdscom-xml#85]
If the sender states that the phrase should end with a line-break, it is not possible today. The phrase-entity should have a new attribute called  "newline". If "newline" has "0", or is omitted, the phrase should have no trailing line-break.If newline has "1" is should have a line-break.

**Comment by Henrich-BGRCI** [comment]
Currently, it is not described how much the information of a Phrase field should be split on different instances. On the one hand, I got examples for reviewing where several sentences were combined to one Phrase instance (having problems with the limit of 1024 characters for FullText), and on the other hand I got examples with splitting a sentence into many instances (even with punctuation marks as an separate instance). Therefore, the import it is not easy to recognize if the instances of a Phrase field should be concatenate or not, and a new attribute "newline" could help.

**Comment by dirk-qualisys** [comment]
Yes, specifying newlines would help. Alternatives:

* Newline attribute as outlined by Thorstein
* Special phrase ID for newlines (no changes in XSD necessary)
* Separate tag for newlines, i.e. a phrase type instance can be either the current phrase tag or the newline tag

The first option connects newlines to the prior phrase, which may make exporting more complicated - at least in our system that would be the case. What do you like best?

**Comment by nils-eska** [comment]
I would appreciate the last option to have a new tag for new lines. From my point of view, this approach is the most transparent and align to html (br-tag)

**Comment by dirk-qualisys** [comment]
Assigned it to 4.3 as the application of a newline attribute or tag would not be backwards compatible. We may certainly change this if we just add a specil phrase ID.

**Comment by dirk-qualisys** [comment]
From today's workshop in Hamburg: Some systems import SDSs to display their content in the target systems, so this enhancement is useful. Phrase ID does not help as catalogues may vary. The group prefers a separate newline tag to be added to the phrase data type.
