### ISSUE TITLE
Rules for how merge-text are used

### ISSUE THREAD

**Issue by thegbom** [esdscom/sdscom-xml#86]
We have made our own rules for how Phrase and MergeText should be used. Maybe it should be it should be some uniform rules on how to use Phrase and MergeText for processing text. Maybe it already exists, and I have not got hold of it.

**Comment by Henrich-BGRCI** [comment]
The basic principal for using MergePhrase is briefly described in the manual for the subsets EDASxChem/Bau (http://www.sdbtransfer.de/app/download/9676194099/Anleitung_EDASxChem_EDASxBau_4.2.0.pdf, page 12 and following) and example code is given in the issue #41.
