### ISSUE TITLE
Classifications without hazard statements

### ISSUE THREAD

**Issue by Feitsch-GmbH** [esdscom/sdscom-xml#94]
ClpClassification -> ClpHazardClassification:
The "ClpHazardStatement" element has minOccurs="1" but there are legal **classifications without hazard statements**, for example
"Org. Perox. G" (legal HazardClassCategoryEnum).

How should an export handle this?
Should minOccurs="1" be changed to "0"?

![26-07-2016 12-15-24](https://cloud.githubusercontent.com/assets/20661875/17137578/2baf7808-533c-11e6-90c3-055411b0fc60.png)

**Comment by nils-eska** [comment]
please see #59
