### ISSUE TITLE
Impure substances

### ISSUE THREAD

**Issue by thegbom** [esdscom/sdscom-xml#95]
In some cases a pure substance has impurities, and should be presented with CAS-number. The impurities should also be added as components. 

A suggestion to how this could be solved is to to remove choice from the tag Composition. That would mean that it can have both substance and mixture at the same time (this is mentioned in the xsd).

**Comment by dirk-qualisys** [comment]
The reason for "choice" will be that REACH Annex II requires any SDS to present either the subsection "substance" or "mixture". Impurities (as well as stabilisers) should be listed in section 3.1. For these, the product identity is sufficient - no concentration ranges or classifications are necessary. This is why SDScom has Substance/HazardousImpurities and Substance/Stabilizer as phrase fields. So the receptient will easily know that the given information is part of 3.1, and thus how the SDS should be printed.

I will comment on alternatives and consequences later, but am happy to read other input.

**Comment by dirk-qualisys** [comment]
a) If we leave everything as-is, we sacrifice the psossibility to transmit a list of impurities or stabilisers, or the composition of an UVCB, in a structured form. 

b) For a structured submission, I suggest that we would take Component out of Mixture (i.e. on the same level as Substance and Mixture) and leave everything else as it is. Component would need to have Concentration optional, and should be enhanced with an enum field for ingredient/additive/impurity (and probably others).

I think the decision (or at least the urgency of the change) may depend largely on the question if systems represent impurities in a structured way today. I would like to ask all readers to comment if this is the case. Our system can use a structured table for this, but mostly users don't.

**Comment by thegbom** [comment]
Ecoonline supports pure substanses with components.

**Comment by nils-eska** [comment]
From today's workshop in Hamburg: The Field "HazardousImpurities" will be changed from type "Phrase" to "Components"

**Comment by dirk-qualisys** [comment]
I think we should assess this more deeply:

- If HazardousImpurities becomes of type Component, then Stabilizer(-s, should be renamed) should as well.
- Component consists of Substance, which would then contain Component again. Do we want such a recursive stucture, which suggests that we are interested of the impurities in the impurities? If not, HazardousImpurities and Stabilizers should be taken out of the Substance type.
- ChemicalProperties appear in Substance in an unstructured way - why? For mixtures, there are structured PhysicalChemicalProperties in addition to this, which seems flawed. The structured representation should be part of Substance.
- How to handle multi-constituents? They basically are a substance legally, but require a representation similar to a mixture.
- CompositionComments exist on two levels.

As a bottom line, I suggest we give composition the following structure:

- CompositionType: Enum of SingleConstituent, MultiConstituent, UVCB, Mixture.
- Ingredients, Impurities and Stabilizers: Each of type Component, while Substance does not include Impurity/Stabilizer/Property information anymore.
- DescriptionOfTheMixture (better "ChemicalCharacterization"?)
- IsDetergent
- CompositionComments

**Comment by thegbom** [comment]
I agreement to all of your points above. I think recrusive structures should be avoided to keep the struktures simple as possible. This will be easiest to implement programatically.

**Comment by dirk-qualisys** [comment]
While I think recursive structure may be neat also for implementation in certain cases, I took the positive feedback from Thorstein to draw up a draft. This uses "Impurity" and "Stabilizer" as an alternative choice to "Substance" (which is for SingleConstituent only). I did not pack chemical properties into the Substance type because this does not make sense for pure substances, where the relevant data is part of section 9 anyway.
![compositiondraft1](https://cloud.githubusercontent.com/assets/4411785/20315257/813a9662-ab5d-11e6-92b0-c82bf063767b.PNG)

I moved IsDetergent to section 15, SpecificProvisionsRelatedToProduct/EuLegislation:
![compositiondraft2](https://cloud.githubusercontent.com/assets/4411785/20315327/c3c8a5a0-ab5d-11e6-9e4f-c0b4c3485c80.PNG)

Do you think this is appropriate? If not, please comment. Otherwise I will commit this in a few days.

**Comment by dirk-qualisys** [comment]
The above pictures don't show the reduced content of Substance in detail. Here it is:
![compositiondraft3](https://cloud.githubusercontent.com/assets/4411785/20315492/5aec112e-ab5e-11e6-8932-ba2046bb3b7b.PNG)

**Comment by nils-eska** [comment]
From my point of view, this approach is fine...

**Comment by dirk-qualisys** [comment]
Re-reading REACH, impurities and additives may occur in single-constituent substances by definition:

> "substance: means a chemical element and its compounds in the natural state or obtained by any manufacturing process, including any additive necessary to preserve its stability and any impurity deriving from the process used, but excluding any solvent which may be separated without affecting the stability of the substance or changing its composition."

To that respect, I have to revise my proposal. The following is closer to Thorstein's original idea and should cover the above definition:
![compositiondraft4](https://cloud.githubusercontent.com/assets/4411785/20447466/474fdf32-addf-11e6-860d-a1edf16393ba.PNG)

OK?
